### ISSUE TITLE
Hatsune Miku Project Diva X (PCSB01007)

### ISSUE THREAD

**Issue by KimYuko** [Vita3K/compatibility#1027]
# App summary
- App name: Hatsune Miku Project diva X
- App serial: PCSB01007
- App version:  01.00

# Vita3K summary
- Version: v0.1.6
- Build number: 2895
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: KimYuko
- OS: Windows 11 pro 64 bits
- CPU: Intel Core i7-4790
- GPU: NVIDIA Quadro K600
- RAM: 16 gb

# Issues
When I start the AiDee game at elegant cloud the game have a infinite loading 

# Screenshots
![](https://?)

# Log
[17:25:32.191] |W| [H264DecoderState::receive]: Error receiving H264 frame: Requires Another Call (AVERROR(EAGAIN)).

# Recommended labels

- A?
- B?
- C?

**Comment by nishinji** [comment]
Plwase look https://github.com/Vita3K/compatibility/issues/270
