### ISSUE TITLE
Robotics;Notes Elite UI issue

### ISSUE THREAD

**Issue by yeogosengsex** [Vita3K/compatibility#1129]
# App summary
- App name: 로보틱스 노츠 엘리트 (Robotics;Notes Elite)
- App serial: PCSH00165
- App version: 

# Vita3K summary
- Version: 0.1.6 
- Build number: 2979
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:  dynamic
- GPU backend:  vulkan

                          

# Test environment summary
- Tested by: ?
- OS: Windows 10/
- CPU: 4790k
- GPU: gtx980
- RAM: 16GB

# Issues
In UI screens such as save, load, tips, back log, map, twipo, there is a phenomenon in which the fps is extremely lowered (30→10~15)

# Screenshots
![스크린샷(1991)](https://user-images.githubusercontent.com/122580174/212213824-c2577676-28b0-44a1-a088-c4bcea8b0473.png)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by nishinji** [comment]
I have tried the Japanese version and I think it is Playable.
TIPS LIST extreme fps drop.

**Comment by othmanead** [comment]
closing as incomplete issue
