### ISSUE TITLE
Glitchy Home Screen

### ISSUE THREAD

**Issue by Benjamin-Sopkin** [Vita3K/compatibility#1137]
Love Live! School idol paradise Vol.1 Printemps [PCSG00422]

# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v0.1.6 2979-eb9baefe
- Build number: ???
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: Dynarmic
- GPU backend: OpenGL

                          

# Test environment summary
- Tested by: Me (Benjamin-Sopkin)
- OS: Windows 10
- CPU: AMD Ryzen 3 1300X Quad-Core
- GPU: NVIDIA GeForce GTX 1660 Ti
- RAM: 32 GB

# Issues

Note that this applies to all three of the games (Printemps, lily white, and BiBi)
The home screen basically is an acid trip. The assets are glitching out in such a manner that it's impossible to tell what is going on. This has been happening for a few months, where before that it was working fine and I had no problems with it
![Screenshot 2023-01-14 141434](https://user-images.githubusercontent.com/18682414/212494870-62cfff75-b4e7-4204-98d1-8fff3d8e6493.png)
. The issue appears to just be a visual bug? I no longer consider this game playable.

# Screenshots
[![](https://?)](https://imgur.com/a/nsMAsmi)

# Log

# Recommended labels

- graphics bug
- Ingame -

https://user-images.githubusercontent.com/18682414/212494971-c3d684e9-e681-42db-a310-abd4f9d4d6dd.mp4

**Comment by Zangetsu38** [comment]
duplicate issue
