### ISSUE TITLE
Soul Sacrifice™ Delta [PCSA00152]

### ISSUE THREAD

**Issue by theheromans** [Vita3K/compatibility#1176]
# App summary
- App name: Soul Sacrifice™ Delta
- App serial: PCSA00152
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3009
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:  Dynarmic
- GPU backend:  OpenGL

                          

# Test environment summary
- Tested by: theheromans
- OS: Windows 10
- CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
- GPU: Intel UHD Graphics
- RAM: 16 GB

# Issues
<Plays, but has a large yellow patch on screen that will not go away.>

# Screenshots
<img width="960" alt="image" src="https://user-images.githubusercontent.com/120532561/218656370-bc4c2273-8fb8-4c92-a722-395367d8cc59.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/120532561/218656534-6eca763b-692d-448a-a9eb-52deae9408e3.png">

# Log

# Recommended labels

In Game-

**Comment by Croden1999** [comment]
repeat issue, check to https://github.com/Vita3K/compatibility/issues/523
