### ISSUE TITLE
enable microphone in dressing room crash on android 

### ISSUE THREAD

**Issue by kittudhanoa** [Vita3K/compatibility#1177]
# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
invail database, and u should push ur issue to https://github.com/Vita3K/Vita3K-Android/issues/new
