### ISSUE TITLE
Genkai Tokki Seven Pirates

### ISSUE THREAD

**Issue by awkwardcultism** [Vita3K/compatibility#118]
# Game summary
- Game name: Genkai Tokki Seven Pirates 限界凸旗 セブンパイレーツ
- Game serial: PCSG00882

# Vita3K summary
- Version: v0.1 
- Build number: 472
- Commit hash: https://github.com/vita3k/vita3k/commit/0fa188f

# Test environment summary
- Tested by: awkwardcultism
- OS: Windows 7
- CPU: Intel i3-4160T
- GPU: Intel HD Graphics 4400
- RAM: 4 GB

# Issues
Crashes with standard Windows "Vita3K.exe has stopped working" popup.
The last entry in the log is:
|W| [unimplemented_impl]:  Unimplemented __aeabi_atexit import called.

# Screenshots

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/2160629/vita3k.log)

# Recommended labels
- Crash

**Comment by IllusionMan1212** [comment]
Just to be sure, are you using a vitamin dump?

**Comment by awkwardcultism** [comment]
Uhh, actually, I am probably not. Sorry.
I'll try again with a vitamin dump.

**Comment by IllusionMan1212** [comment]
Well, sorry for the confusion but you're not supposed to use vitamin dumps or nonpdrm dumps as the emulator only supports maidumps.
so if you have any maidumps around use those.

**Comment by IllusionMan1212** [comment]
No problem :)
