### ISSUE TITLE
Fireballs aren't visible. All other graphics look fine.

### ISSUE THREAD

**Issue by SHIVAMKumar69god** [Vita3K/compatibility#1180]
Fireballs aren't visible. All other graphics look fine.
![image](https://user-images.githubusercontent.com/2209573/214858544-b1409c12-9d3e-4121-8383-480449aaed75.png)

_Originally posted by @ChaosSlave51 in https://github.com/Vita3K/compatibility/issues/555#issuecomment-1405068501_

**Comment by Croden1999** [comment]
invaild database.

**Comment by SHIVAMKumar69god** [comment]
> ```
>           Fireballs aren't visible. All other graphics look fine.
> ```
> 
> ![image](https://user-images.githubusercontent.com/2209573/214858544-b1409c12-9d3e-4121-8383-480449aaed75.png)
> 
> _Originally posted by @ChaosSlave51 in [#555 (comment)](https://github.com/Vita3K/compatibility/issues/555#issuecomment-1405068501)_
