### ISSUE TITLE
Shakedown Hawaii (PCSB01375)

### ISSUE THREAD

**Issue by Rhro1702** [Vita3K/compatibility#1198]
# App summary
- App name: Shakedown Hawaii
- App serial: PCSB01375
- App version: 1.01

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues
 shakedown hawaii colour screen have bug and the game is bug laggy.

# Screenshots
![](https://media.discordapp.net/attachments/577624167541637158/1075713423062614036/mobizen_20230216_153055.mp4)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by nishinji** [comment]
At the very least, please provide screenshots.
And logs if possible.

**Comment by Rhro1702** [comment]
> At the very least, please provide screenshots. And logs if possible.

https://media.discordapp.net/attachments/577624167541637158/1075713423062614036/mobizen_20230216_153055.mp4

Here video

**Comment by Zangetsu38** [comment]
issue is invalid, when you create issue, write all info asked
