### ISSUE TITLE
Batman™: Arkham Origins Blackgate [PCSE00269]

### ISSUE THREAD

**Issue by Dimas0008** [Vita3K/compatibility#1201]
# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Dimas0008** [comment]
the graphics is a bug

**Comment by Zangetsu38** [comment]
> the graphics is a bug

you issue is totaly invalid, you  have writed nothing
