### ISSUE TITLE
I can't install this. I get "no compatible content" on pretty much every rom

### ISSUE THREAD

**Issue by onfterh6** [Vita3K/compatibility#1208]
I can't install this. I get "no compatible content" on pretty much every rom

_Originally posted by @gareth198069 in https://github.com/Vita3K/compatibility/issues/1199#issuecomment-1433151197_

**Comment by Zangetsu38** [comment]
Stop open issue no relate repo

**Comment by MrSovann** [comment]
https://github.com/Vita3K/compatibility/issues/1199

**Comment by wesley0561** [comment]
![Screenshot_20231007-125226_Vita3K](https://github.com/Vita3K/compatibility/assets/147265701/8fd02bd6-d346-4716-8c79-69574f09b4d0)
`
