### ISSUE TITLE
Fate/EXTELLA [PCSG00600]

### ISSUE THREAD

**Issue by mostazaniikkkk** [Vita3K/compatibility#1210]
# App summary
- App name: Fate/Extella
- App serial: PCSG00600
- App version: 1.00

# Vita3K summary
- Version: v1.6.0-3
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:               Dynamic
- GPU backend:  Vulkan

                          

# Test environment summary
- Tested by: Mostazaniikkkk
- OS: Android 11
- Phone: Poco x3 Pro

# Issues

-It don't load any 3D model, only a white space
-Verry low performance

# Screenshots
![](https://?)
![Screenshot_2023-02-17-00-27-23-026_org vita3k emulator](https://user-images.githubusercontent.com/56448442/219542747-cc1b88f1-df21-4f75-a5a0-568dd90e0d0c.jpg)

# Recommended labels

- Ingame -

**Comment by Zangetsu38** [comment]
using pc version for test and repport issue, android version for now have too much diference compare pc ver
