### ISSUE TITLE
Secret of Mana [PCSE01153]

### ISSUE THREAD

**Issue by Pogipoint123** [Vita3K/compatibility#1232]
![Screenshot_20230218-134723212](https://user-images.githubusercontent.com/125525625/219844691-70fadbee-605f-433c-85e1-a0be6f3679b8.jpg)
![Screenshot_20230218-134616158](https://user-images.githubusercontent.com/125525625/219844697-ca6462b9-c9e3-41b3-989e-be19e8069df9.jpg)
![Screenshot_20230218-134604173](https://user-images.githubusercontent.com/125525625/219844703-f7513edd-cbcd-4d5f-aa8d-bb2809760c42.jpg)
![Screenshot_20230218-134547637](https://user-images.githubusercontent.com/125525625/219844709-31eb4350-a009-4c5f-992d-a37b9b23ad9e.jpg)

![Screenshot_20230218-134616158](https://user-images.githubusercontent.com/125525625/219844655-0835282d-5b15-435a-93b0-c4703b422c34.jpg)
![Screenshot_20230218-134547637](https://user-images.githubusercontent.com/125525625/219844670-acd98869-7258-41da-9e9e-23712b69ded3.jpg)
![Screenshot_20230218-134616158](https://user-images.githubusercontent.com/125525625/219844673-d086d085-98a9-4850-a162-4880dda350cd.jpg)

# App summary
- App name:Secret of Mana
- App serial:PCSE01153 
- App version:1.00

# Vita3K summary
- Version:1.6.0-3(3)
- Build number:3
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:Dynarmic              
- GPU backend:Vulkan 

                          

# Test environment summary
- Tested by: myself 
- OS:Android 10(Corvus)A10.0stable
- CPU:Octa-core 2.2 GHz Kryo 260 
- GPU:Adreno 616
- RAM:6GB

# Issues
the game running 60fps no graphical issues on Androidvita3k but it crush after long play and continue again 

# Screenshots_20230218-134616158](https://user-images.githubusercontent.com/125525625/219844655-0835282d-5b15-435a-93b0-c4703b422c34.jpg)
![Screenshot_20230218-134547637](https://user-images.githubusercontent.com/125525625/219844670-acd98869-7258-41da-9e9e-23712b69ded3.jpg)
![Screenshot_20230218-134616158](https://user-images.githubusercontent.com/125525625/219844673-d086d085-98a9-4850-a162-4880dda350cd.jpg)

# Log

# Recommended labels
<!--
https://github.com/Vita3K/compatibility/labels/Playable
- 
- playable

**Comment by Pogipoint123** [comment]
please update this on compatibility to playable

**Comment by Zangetsu38** [comment]
is duplicate, using original sisue, and report only pc version for now
#470
