### ISSUE TITLE
Persona 4 Golden [PCSE00120]

### ISSUE THREAD

**Issue by GitubJin** [Vita3K/compatibility#1237]
# Game summary
Game name: Persona 4 Golden
Game serial:  PCSE00120

# Vita3K summary
- Version: v0.1.6.3020
- Build number: a4ded14b
- CPU backend: Dynarmic
- GPU backend: Vulkan                           

# Test environment summary
- Tested by: me
- Hardware: Steam Deck
- OS: KDE Plasma, Kernel Version 5.13.0-valve36-1-neptune (64bit)
- APU: AMD Custom 0405
- RAM: 16 GB

# Issues
Crashes after the first cutscene in the beginning of game.

# Recommended labels
- Crash
- Intro

**Comment by Croden1999** [comment]
it is playable

**Comment by GitubJin** [comment]
> it is playable

no, because it crashes everytime

**Comment by Croden1999** [comment]
> > it is playable
> 
> no, because it crashes everytime

maybe ur game issue, not compat issue. i used nonpdrm, it is okay, no any problem.

**Comment by GitubJin** [comment]
> > > it is playable
> > 
> > 
> > no, because it crashes everytime
> 
> maybe ur game issue, not compat issue. i used nonpdrm, it is okay, no any problem.

same game PCSE00120? on steam deck

**Comment by Croden1999** [comment]
> > > > it is playable
> > > 
> > > 
> > > no, because it crashes everytime
> > 
> > 
> > maybe ur game issue, not compat issue. i used nonpdrm, it is okay, no any problem.
> 
> same game PCSE00120? on steam deck

I no have steam deck, but i tested this game same as windows/android.
![image](https://user-images.githubusercontent.com/61804715/219857234-57fd7231-8021-40a4-9052-542c6365c5cb.png)

**Comment by Croden1999** [comment]
and ur issue is duplicate issue, look this https://github.com/Vita3K/compatibility/issues/155

**Comment by GitubJin** [comment]
> and ur issue is duplicate issue, look this #155

wouldnt say its the same, I can passed the intro and I can start a new game
