### ISSUE TITLE
Persona 4 Golden [PCSB00245]

### ISSUE THREAD

**Issue by Ahmedadel132** [Vita3K/compatibility#1246]
Persona 4 Golden

# App summary
- App name: Persona 4 Golden
- App serial: [PCSE00245]
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/
- CPU backend: Dynarmic          

# Test environment summary
- Tested by: Ahmedadel132
- OS: Android 13
- CPU: Octa-core (2×2.4 GHz Cortex-A78 & 6×2.0 GHz Cortex-A55)
- GPU: Mali-G68
- RAM: 8 GB

# Issues
The game works perfectly fine but there are some video problems but they rarely happen , overall the game is playable

# Screenshots

![Screenshot_20230219_162400_Vita3K](https://user-images.githubusercontent.com/125455905/219951679-68184b9a-b82f-4353-a358-b8845ff48c82.jpg)
 
![Screenshot_20230219_162452_Vita3K](https://user-images.githubusercontent.com/125455905/219951706-ea815acb-10e7-4317-bb40-d3398e06d974.jpg)

![Screenshot_20230219_162609_Vita3K](https://user-images.githubusercontent.com/125455905/219951725-ef9b92c1-77c2-484d-9f69-b6d6f4024e59.jpg)

# Log

# Recommended labels

- Playable 
- video player bug 
- C?

**Comment by Zangetsu38** [comment]
game have already issue here, update it 
[#pers](https://github.com/Vita3K/compatibility/issues/6)
