### ISSUE TITLE
PERSONA 4 GOLDEN AUDIO CRACKLING

### ISSUE THREAD

**Issue by suhailiachmad** [Vita3K/compatibility#1247]
# Persona 4 Golden

# App summary
- App name: Persona 4 Golden
- App serial: PCSE00120
- App version: 1.00

# Vita3K summary
- Version: v1.0.6-3
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:      Dynarmic        
- GPU backend: Vulkan 

                          

# Test environment summary
- Tested by: suhailiachmad
- OS: Android
- CPU: Mediatek Helio G85
- GPU: Mali-G52 MC2
- RAM: 6 GB

# Issues

The Audio keep crackling as if it was comes out from a bad speaker even when the game runs at fullspeed. 
# Screenshots
![](https://?)

# Log

# Recommended labels

- Playable

**Comment by Zangetsu38** [comment]
issue already exist here https://github.com/Vita3K/compatibility/issues/155
