### ISSUE TITLE
LEGO® MARVEL Super Heroes: Universe in Peril [PCSE00250]

### ISSUE THREAD

**Issue by ForgetSora** [Vita3K/compatibility#1252]
# App summary
- App name: LEGO® MARVEL Super Heroes: Universe in Peril
- App serial: PCSE00250
- App version: US

# Vita3K summary
- Version: v1.6.0-3
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: ForgetSora
- OS: Android
- CPU: Qualcom Snapdragon 680 
- RAM: 6GB

# Issues
The game runs well at start, but textures, voices and sounds are very bug. When the gameplay starts the game crash

# Screenshots
![]![Screenshot_2023-02-19-20-41-41-046_org vita3k emulator](https://user-images.githubusercontent.com/125828864/219971842-9fe22945-f44a-46c5-beb1-b90fa1324cee.jpg)
![Screenshot_2023-02-19-20-43-12-709_org vita3k emulator](https://user-images.githubusercontent.com/125828864/219971879-2b6af238-4b6b-4629-afa1-efd95e329ae9.jpg)
![Screenshot_2023-02-19-20-43-19-623_org vita3k emulator](https://user-images.githubusercontent.com/125828864/219971901-71d9b271-f2cb-4a60-b5ba-28f25cfd4c0b.jpg)
# Log

# Recommended labels

- Grafics Bug
- Audio Bug
- Crash

**Comment by Zangetsu38** [comment]
Need test pc version and no Android, no using Android version for issue curently

**Comment by ForgetSora** [comment]
Oh... Sorry, i didn't know that

**Comment by Zangetsu38** [comment]
no worry, is just android version have LOT diference commpare pc lol

**Comment by PowerGamesBrasil** [comment]
https://drive.google.com/file/d/1CltL6W7h-NM0eW-9PCiOSuAyo9fp3LHZ/view?usp=drivesdk

Use This Driver, After History Screen The Game Will Run.
I Used The POCO X3 PRO.

**Comment by PowerGamesBrasil** [comment]
New Link Corrected, Please Check It To See If There Are Any Problems!

**Comment by PowerGamesBrasil** [comment]
New Driver :
https://mega.nz/file/b6wiwIgB#7fhCsevvlqpLzd7hJqCKMHBZQKqoba590w-vMIIrv_8

**Comment by Croden1999** [comment]
should close this issue.

**Comment by othmanead** [comment]
not accurate reporting

**Comment by Ruslanhdhxxjdj** [comment]
Где скачать
?
