### ISSUE TITLE
Miracle Girls Festival [PCSG00610]

### ISSUE THREAD

**Issue by tetorapott** [Vita3K/compatibility#1259]
# App summary
- App name: Miracle Girls Festival
- App serial: PCSG00610
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3024
- Commit hash: https://github.com/Vita3K/Vita3K/commit/09dd3e81
- CPU backend: Dynarmic
- GPU backend: Vulkan
                          

# Test environment summary
- Tested by: tetorapott
- OS: Windows 11 Pro
- CPU: 12th Gen Intel(R) Core(TM) i7-12700K
- GPU: NVIDIA GeForce RTX 3070
- RAM: 32.0 GB

# Issues
playable
the back monitor doesn't display

# Screenshots
![タイトルなし](https://user-images.githubusercontent.com/124598498/220377892-733bdbcb-ba61-43fe-8b28-ceaf19452086.png)
![タイトルなし2](https://user-images.githubusercontent.com/124598498/220378189-433ce9a6-5853-4717-8adf-f6958ed12bb6.png)

OpenGL
- "Disable surface sync" OFF, the back monitor display
- slowly

![タイトルなし3](https://user-images.githubusercontent.com/124598498/220757967-27dc827d-bfd6-45b0-b96f-19a422368a37.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/10794643/vita3k.log)

# Recommended labels

- Playable
- vulkan issue
- video player bug?

**Comment by AccordiaDusk** [comment]
This is the only game that I hope to play on the project. Can't wait for it to be playable on the Android version. Thanks for the update tho.

**Comment by Zangetsu38** [comment]
duplicate issue, using original #600
