### ISSUE TITLE
Bloodstained: Curse of the Moon [PCSB01250]

### ISSUE THREAD

**Issue by Dennis-co** [Vita3K/compatibility#1263]
# App summary
- App name: Bloodstained: Curse of the Moon
- App serial: PCSB01250
- App version:1.00 

# Vita3K summary
- Version: v v0.1.6
- Build number:3026
- Commit hash: https://github.com/vita3k/vita3k/commit/39f79451t
- CPU backend: Dynamic            
- GPU backend: Vulkan and OpenGl 

                          

# Test environment summary
- Tested by: Dennis-co
- OS: Windows 11
- CPU: AMD Phenom x6 1055T 2.80 GHz
- GPU: GTX 1050 2 GB
- RAM: 16 GB

# Issues
- Sprite errors at the beginning

# Screenshots
![Vita3K v0 1 6 3026-39f79451 _ Bloodstained_ Curse of the Moon (PCSB01250) _ Vulkan _ 60 FPS (17 ms) _ 1920x1088  23_2_2023 2_15_30](https://user-images.githubusercontent.com/126137618/220826679-4ed3dc47-3cba-4830-bdd3-c4464694d0d2.png)
![Vita3K v0 1 6 3026-39f79451 _ Bloodstained_ Curse of the Moon (PCSB01250) _ Vulkan _ 60 FPS (17 ms) _ 1920x1088  23_2_2023 2_16_47](https://user-images.githubusercontent.com/126137618/220826703-e5507040-71fc-42da-9b99-5a4374d71e2f.png)
![Vita3K v0 1 6 3026-39f79451 _ Bloodstained_ Curse of the Moon (PCSB01250) _ Vulkan _ 60 FPS (17 ms) _ 1920x1088  23_2_2023 2_17_17](https://user-images.githubusercontent.com/126137618/220826714-bc1dffee-c401-47c1-8a34-52f779f73eb7.png)

# Log

# Recommended labels
- Playable

**Comment by Zangetsu38** [comment]
thx, add your screen and report in original issue 👌
