### ISSUE TITLE
Uncharted: Golden Abyss™ [PCSA00029]

### ISSUE THREAD

**Issue by Gty1221** [Vita3K/compatibility#1272]
# App summary
- App name: Uncharted: Golden Abyss™
- App serial: PCSA00029
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3028
- Commit hash: https://github.com/vita3k/vita3k/commit/8744f031
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Gty1221 
- OS: Windows 10
- CPU: i3 3220
- GPU: NVIDIA GT 1030
- RAM: 8 GB

# Issues

Optimization and graphical issue

# Screenshots

# Log

# Recommended labels

- Ingame -

**Comment by othmanead** [comment]
Not enough information
