### ISSUE TITLE
Uncharted Golden Abyss booting and closing emulator fix

### ISSUE THREAD

**Issue by Johnzx07** [Vita3K/compatibility#1273]
# App summary
- App name: Uncharted: Golden Abyss™
- App serial: PCSF00001
- App version: 1.03

# Vita3K summary
- Version: v0.1.6
- Build number: 3028
- Commit hash: https://github.com/vita3k/vita3k/commit/8744f03 
- CPU backend:  Dynarmic            
- GPU backend: Vulkan

                          

# Test environment summary
- Tested by: Te New Game+ (Johnzx07)
- OS: Windows 11 Pro
- CPU: AMD Ryzen 95950X
- GPU: NVIDIA RTX 3090 Ti
- RAM: 32GB

# Issues

I wasn't able to run the game properly. After trying many settings the game will launch and close the emulator.  The only workaround that fixed my issue was to launch Vita3k as an admin. After doing so the game opened properly.

Note: My current CPU is a 16-core 32 Threads, running vita3k as admin might be only applicable to a CPU with more than 8-10 cores.

Other settings to take into consideration for PC:
-Resolution 5X (This is a must or there will be many visual glitches)
-Render: Vulkan
-AF 16X
-CPU: Dynamic

Possible fixes: If the game is running with many missing graphics you will have to remove all shader cache and run the game with the settings above.

# Screenshots
![Screenshot 2023-02-24 144848](https://user-images.githubusercontent.com/96490408/221277222-94d163f2-05b5-4503-97c2-27a2a469688e.png)

![Screenshot 2023-02-24 145208](https://user-images.githubusercontent.com/96490408/221277499-cf53315b-2afb-487b-8202-934a338aca00.png)

[vita3k.log](https://github.com/Vita3K/compatibility/files/10828153/vita3k.log)

# Recommended labels

- ingame+
- Audio bug
- Graphics bug

**Comment by Zangetsu38** [comment]
duplicate issue here
https://github.com/Vita3K/compatibility/issues/208
