### ISSUE TITLE
Menu & Text Menu disappear in Street Figher X Tekken (PCSB00144)

### ISSUE THREAD

**Issue by TommyThuyen** [Vita3K/compatibility#1284]
Menu & Text Menu disappear in Street Figher X Tekken (PCSB00144)

# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: 0.1.6
- Build number: 3028
- CPU backend:  Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: me
- OS: Windows 11
- CPU: AMD 6800U
- GPU: AMD
- RAM: 32 GB

# Issues
Menu Highlighted & Text Menu disappear in Street Figher X Tekken (PCSB00144)

# Screenshots
![Screenshot_20230225_030100](https://user-images.githubusercontent.com/122481706/221366745-428bad99-a53c-4c34-9618-928fae6bdab1.png)
![Screenshot_20230225_094130](https://user-images.githubusercontent.com/122481706/221366759-d6f2f63d-2041-40f8-8eed-c28d7bba31a2.png)
![Screenshot_20230225_094323](https://user-images.githubusercontent.com/122481706/221366769-e420480c-0e94-4cb8-9ea3-bee607153ae3.png)
![Screenshot_20230225_094256](https://user-images.githubusercontent.com/122481706/221366796-62bf4f2c-2c2f-4690-a12e-43df953ece77.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/10831613/vita3k.log)

**Comment by Zangetsu38** [comment]
Issue already exist #1207

**Comment by shahroze786** [comment]
ok
