### ISSUE TITLE
DIABOLIK LOVERS: LUNATIC PARADE [PCSG00826]

### ISSUE THREAD

**Issue by spookyblackcats** [Vita3K/compatibility#1292]
# App summary
- App name: DIABOLIK LOVERS: LUNATIC PARADE
- App serial: PCSG00826
- App version: 1.0

# Vita3K summary
- Version: v0.1.6
- Build number: 3029
- Commit hash: https://github.com/vita3k/vita3k/commit/#968
- CPU backend:  Unicorn and Dynarmic.
- GPU backend: OpenGL

                          

# Test environment summary
- Tested by: spookyblackcats
- OS: Windows 11
- CPU: Intel
- GPU: Intel
- RAM: 16.0 GB

# Issues
Game runs with noticeable graphical issues, including but not limited to:
- character sprites appearing glitched and/or not at all
- backgrounds appearing black
- characters may appear fully or partially blue/discolored
- sprite facial animations may appear alone
- characters have the sprite of another character mixed with theirs

# Screenshots
_sprite shows only eyes + mouth_
<img width="719" alt="image" src="https://user-images.githubusercontent.com/125928438/221443029-e173ee08-06c2-4333-8c7a-291ecf0406f1.png">
_sprite discoloration_
<img width="718" alt="image" src="https://user-images.githubusercontent.com/125928438/221443183-24ef22ce-238c-4a77-a71d-5215ef2d4190.png">
_background not appearing + sprite discoloration_
<img width="720" alt="image" src="https://user-images.githubusercontent.com/125928438/221443239-bf8f08b4-732d-445a-88d1-435f0171d71f.png">
_background not appearing + sprite errors + background not appearing_
<img width="718" alt="image" src="https://user-images.githubusercontent.com/125928438/221445406-99244ed9-d6fb-4dbd-b8c7-d8852cf58b19.png">
_a character's sprite discolored + parts are replaced w/ another character's + background not appearing_
<img width="720" alt="image" src="https://user-images.githubusercontent.com/125928438/221445488-9aee0ff3-f00b-43c4-8cf0-f4c6f47e6a2b.png">

# Log
[vita3k.txt](https://github.com/Vita3K/compatibility/files/10835141/vita3k.txt)

# Recommended labels

- graphics bug
- playable

**Comment by Zangetsu38** [comment]
You can can look if surface sync is enable ?

**Comment by spookyblackcats** [comment]
> You can can look if surface sync is enable ?

Surface sync was enabled--even when disabled, still the same. Not having any luck playing around with some other settings either.
I'm curious as to what causes this to happen, though. I'm not very knowledgeable on these things, haha.

**Comment by Zangetsu38** [comment]
Using original issue #452
