### ISSUE TITLE
LEGO® Legends of Chima™: Laval's Journey [PCSE00237]

### ISSUE THREAD

**Issue by AshlehGi** [Vita3K/compatibility#1295]
Android 

# App summary
- App name:LEGO CHIMA ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              
- GPU backend: 

                          

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 8 GB

# Issues

Crash smartphone strong xiaomi 11t video on youtube this game not crashing but on my device his crash
# 

> Screenshots](![](https://?)). 

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
test only pc version  and issue is full empty here
