### ISSUE TITLE
Soul Sacrifice™ Delta [PCSA00152]

### ISSUE THREAD

**Issue by Amircael** [Vita3K/compatibility#1299]
# App summary
- App name: soul sacrifice delta 
- App serial: [PCSA00152]
- App version: 1.10

# Vita3K summary
- Version: 0.1.6 
- Build number: 3030
- Commit hash: https://github.com/vita3k/vita3k/commit/810b2be8
- CPU backend: Dynarmic 
                          

# Test environment summary
- Tested by: Amircael 
- OS: Android 12
- CPU: exynos990 
- GPU: Mali G77
- RAM: 4 Go

# Issues

Graphics probleme and sounds to
# Screenshots
![](https://?)
![Screenshot_20230227-224155_Vita3K](https://user-images.githubusercontent.com/126521531/221712851-5ca5e472-3d61-48e4-835b-8bfcf8f5d455.jpg)
![Screenshot_20230227-224112_Vita3K](https://user-images.githubusercontent.com/126521531/221712857-a67e0ff5-a747-4d23-a959-764526efcf3c.jpg)
![Screenshot_20230227-224049_Vita3K](https://user-images.githubusercontent.com/126521531/221712860-bfe2e105-9df0-4266-91f4-cf9bb9f2189a.jpg)
![Screenshot_20230227-224037_Vita3K](https://user-images.githubusercontent.com/126521531/221712862-468674fe-cbc3-40bd-bf9c-66e4a4d61d7a.jpg)
![Screenshot_20230227-224000_Vita3K](https://user-images.githubusercontent.com/126521531/221712867-f00905b9-78e1-49e8-b634-c881a71704b9.jpg)

# Log
vita3K.log
# Recommended labels

- ingame -
- sounds bug
- graphic bug

**Comment by Zangetsu38** [comment]
no report test on android
is for pc only actually
on pc state is very diferent

**Comment by Amircael** [comment]
Ok

**Comment by Zangetsu38** [comment]
> Ok

if you can retry same game in pc version and update your issue

**Comment by Croden1999** [comment]
your issue is duplicate issue, look this issue https://github.com/Vita3K/compatibility/issues/523
