### ISSUE TITLE
STREET FIGHTER X TEKKEN [PCSE00005]

### ISSUE THREAD

**Issue by Arj132** [Vita3K/compatibility#1307]
# App summary
- App name: STREET FIGHTER X TEKKEN
- App serial: PCSE00005
- App version: v1.0

# Vita3K summary
- Version: v0.1.6
- Build number: 3030-810b2be8
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- OS: Android 12
- CPU: Mediatek Dimensity 700
- GPU: Mali ARM G57 MC2
- RAM: 6GB

# Issues
Skills effects are invisible (ex:hadouken can't be seen but it hits the enemy though)

**Comment by Zangetsu38** [comment]
sorry, no test game with android version, only pc for now
