### ISSUE TITLE
Uncharted: Golden Abyss™ [PCSA00029]

### ISSUE THREAD

**Issue by ahmadmax13** [Vita3K/compatibility#1309]
# App summary
- App name: Uncharted: Golden Abyss™
- App serial: PCSA00029
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3032
- Commit hash: https://github.com/vita3k/vita3k/commit/e2b07dc4
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: Adorait.com 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 7 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
what is the issue? need detailed information
