### ISSUE TITLE
NFS Most Wanted on Android

### ISSUE THREAD

**Issue by AAAGroth** [Vita3K/compatibility#1340]
The game seems to have a playable performance but the game has no sound and the image its not rendered properly.

# App summary
- App name: Need for Speed: Most Wanted
- App serial: PCSE00089
- App version: 1

# Vita3K summary
- Version: [Vita3K Android Release 3
- Build number: v3
- Commit hash: (https://github.com/Vita3K/Vita3K-Android/releases/tag/v3)
- CPU backend:  Dynarmic
- GPU backend:  Vulkan 
- GPU Driver: turnip-v25-adpkg                          

# Test environment summary
- Tested by: AAAGroth
- OS: Android 13
- CPU: Snapdragon 865
- GPU: Adreno 650
- RAM: 6 GB LPDDR5

# Issues
The game has a blue tint in the image in the cutscenes, when reaching gameplay shaders start to be compilated and there is just a blue and green image, soon after the app crash and there is no sound

# Screenshots
![VideoCapture_20230306-115523](https://user-images.githubusercontent.com/124539831/223147138-2804b865-b013-4af7-951c-c98f133f1035.jpg)
![VideoCapture_20230306-115535](https://user-images.githubusercontent.com/124539831/223147193-aa0dac63-5ace-4d56-93f8-6dbf578fbbf3.jpg)
![VideoCapture_20230306-115531](https://user-images.githubusercontent.com/124539831/223147209-cf72c716-7bd3-4a77-b14a-a6a086e4ec20.jpg)
![VideoCapture_20230306-115515](https://user-images.githubusercontent.com/124539831/223147218-67ddbab8-91af-40b9-ac2f-adae79cffd66.jpg)
![VideoCapture_20230306-115503](https://user-images.githubusercontent.com/124539831/223147226-5236e7a7-4068-4162-bf65-2b101eec8520.jpg)

# Recommended labels
Ingame -
Graphics bug

**Comment by elPrimoDorado** [comment]
you forgot the label invalid issue :v

**Comment by AAAGroth** [comment]
> you forgot the label invalid issue :v

Srry, idk how to fix it

**Comment by Croden1999** [comment]
compat issue is not for android version, is for pc version
