### ISSUE TITLE
Uncharted: El Abismo de Oro™ Demo [PCSF00119]

### ISSUE THREAD

**Issue by nanomasternoob2** [Vita3K/compatibility#1385]
# App summary
- App name: Uncharted: El Abismo de Oro™ Demo
- App serial: PCSF00119
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3081
- Commit hash: https://github.com/vita3k/vita3k/commit/8b13982b
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 3 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
invalid issue and commit
