### ISSUE TITLE
Catherine Full Body Graphical Errors 

### ISSUE THREAD

**Issue by GabrielP27i** [Vita3K/compatibility#1386]
# App summary
- App name: キャサリン・フルボディ
- App serial: PCSG01179
- App version: 1.00

# Vita3K summary
- Version: v4
- Build number: 1.6.0-4

                          

# Test environment summary
- Tested by: GabrielP27i
- DEVICE: Motorola One Vision
- OS: Android 11
- GPU: Mali-G72
- RAM: 4 GB

# Issues
The game runs smoothly by the way, but the problem is the several graphical errors/bugs 

# Screenshots
![](https://?)
![Screenshot_20230326-132026](https://user-images.githubusercontent.com/128992225/227790205-4952bf12-1c52-40fa-9c99-b4d1d3a44c92.png)

**Comment by Croden1999** [comment]
invaild issue, compat not for android, is for pc
