### ISSUE TITLE
Xenon Valkyrie  [PCSE01191]

### ISSUE THREAD

**Issue by resaaa2023** [Vita3K/compatibility#1399]
# App summary
- App name: Xenon Valkyrie+
- App serial: PCSE01191
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3081
- Commit hash: https://github.com/vita3k/vita3k/commit/8b13982b
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: resaaa2023
- OS: Android 12
- CPU: Mediatek Helio G96
- GPU: Mali-G57 MC2
- RAM: 7 GB

# Issues
Playable without Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- Playable
- No Issues

**Comment by Croden1999** [comment]
invaild commit, compat issue is not for Android, is for PC version

**Comment by Zangetsu38** [comment]
@othmanead i no have this version, if you can test it
