### ISSUE TITLE
Soul Sacrifice™ Delta [PCSA00152]

### ISSUE THREAD

**Issue by jusagi** [Vita3K/compatibility#1403]
# App summary
App name: soul sacrifice delta
App serial: [PCSA00152]
App version: 1.10

# Vita3K summary
Version: 0.1.6
Build number: 3090
Commit hash: https://github.com/Vita3K/Vita3K/commit/810b2be8
CPU backend: Dynarmic

# Test environment summary
Tested by: jusagi
OS: Window 11
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU: NVIDIA GeForce RTX 3060
RAM: 16GB

# Issues
Mind's eyes doesn't work with Enemy's HP outline, and interest spots like offerring renewals or Soul Shard missions.

# Screenshots
----- No outliner
![image](https://user-images.githubusercontent.com/33427391/229271184-bdb09ab4-501f-4509-9003-1a6187e714d3.png)
----- Spot of interest
![image](https://user-images.githubusercontent.com/33427391/229271205-6c6ec624-830c-49ea-a695-1b35398e4efa.png)

_How it should've been_
![image](https://user-images.githubusercontent.com/33427391/229271213-c7f80dcf-bdd8-4106-9c37-ebf98cee3d42.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11128687/vita3k.log)

# Recommended labels

Playable
Graphic bug

**Comment by nishinji** [comment]
already exist
https://github.com/Vita3K/compatibility/issues/523

**Comment by jusagi** [comment]
Hi nishinji,

Thank you for checking on this issue,
I've checked other tickets that are from #523 , but mostly they're having problem post prologue and stuff, even tested on android.
But what about my case? Does it related to in-game graphic or emulator's setting may I ask?

**Comment by xcx441700** [comment]
Use version 3586 , do not  tick the "disable surface sync" in GPU setting, that should works.
![Screenshot 2025-01-15 194724](https://github.com/user-attachments/assets/ce7ad9cb-ea91-4b56-9f15-9d38e7bef383)
![Screenshot 2025-01-15 195335](https://github.com/user-attachments/assets/cc5e465e-b607-4b0d-80cd-abcb62dd6644)
