### ISSUE TITLE
Bullet Girls Phantasia [PCSH10099]

### ISSUE THREAD

**Issue by Luckyseven00** [Vita3K/compatibility#1409]
# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues
 force to close the apps on mali device 

# Screenshots
![](https://?)
![Screenshot_20230402-072938](https://user-images.githubusercontent.com/126804240/229322715-430a54d1-6ca5-4ef1-8108-020c58c8e8b6.jpg)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
duplicate and invalid issue
