### ISSUE TITLE
DYNASTY WARRIORS NEXT [PCSB00089]

### ISSUE THREAD

**Issue by Marco2000XboxBrasil** [Vita3K/compatibility#1414]
# App summary
- App name: DYNASTY WARRIORS NEXT
- App serial: PCSB00089
- App version: 1.01

# Vita3K summary
- Version: v0.1.6
- Build number: 3091
- Commit hash: https://github.com/vita3k/vita3k/commit/e3956248
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Marco 
- OS: Windows 11Pro
- CPU: Intel Core i3-10100 @4.30GHz
- GPU: NVIDIA GTX 1060 6GB Expedition 
- RAM: 12 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A

**Comment by Marco2000XboxBrasil** [comment]
Jogável e em 60FPS

**Comment by Garruk2k22** [comment]
Dueling system problem

**Comment by Croden1999** [comment]
u need write more detail
