### ISSUE TITLE
Dungeon Travelers 2: TRL&tMS [PCSE00693]

### ISSUE THREAD

**Issue by jinniper** [Vita3K/compatibility#1415]
# App summary
- App name: Dungeon Travelers 2: The Royal Library & the Monster Seal
- App serial: PCSE00693
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3091
- Commit hash: https://github.com/vita3k/vita3k/commit/e3956248
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: jinniper
- OS: Windows 11
- CPU: Intel(R) Core(TM) i5-12400F   2.50 GHz
- GPU: NVIDIA GeForce GTX 3060
- RAM: 32 GB

# Issues
Title appears to have stable 30fps in most areas / situations I've tested _besides_ menu overlays, large entity number combat encounters, etc. It seems to be tied only to the number / length of the list of things it needs to detail. i.e. the Equipment menu where there can be dozens of characters listed, in shops that have a plethora of list entries, so on and so forth. If single digit fps is already known in these circumstances, do please close / delete this Issue.

# Screenshots
![image](https://user-images.githubusercontent.com/125017673/229623442-6f0244f0-a7d3-425b-b2a0-9f3529a23c5e.png)
(^ Plentiful items listed vs. when I clear the inventory out to a degree)
![image](https://user-images.githubusercontent.com/125017673/229623708-f5c23494-d138-440e-bf5a-e504cd99fa79.png)

# Log
Nothing to note
# Recommended labels
- slow
- Ingame +

**Comment by Zangetsu38** [comment]
no  invalide, but duplicat yes
@jinniper update issue original #352
