### ISSUE TITLE
Football Manager Classic 2014 EU

### ISSUE THREAD

**Issue by Mizzuman** [Vita3K/compatibility#1416]
# App summary
- App name: Football Manager Classic 2014 EU
- App serial: PCSB00357
- App version: 2014

# Vita3K summary
- Version: v4
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: AMD/Intel? Intel
- GPU: AMD/NVIDIA/Intel? Intel
- RAM: ? 8 GB

# Issues
the game starts but immediately freezes at the screen

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
Compat issue submit not for android, is for PC

**Comment by Mizzuman** [comment]
> Problema di compatibilità inviato non per Android, è per PC

Sorry I got the problem wrong and for android

**Comment by Croden1999** [comment]
> Sorry I got the problem wrong and for android

but ur issue is invaild

**Comment by Mizzuman** [comment]
> > Sorry I got the problem wrong and for android
> 
> but ur issue is invaild

Allora lo proverò  anche su PC e ti farò sapere grazie

**Comment by Croden1999** [comment]
> Allora lo proverò anche su PC e ti farò sapere grazie

android version is branch, no create log file on android

**Comment by Mizzuman** [comment]
> > Allora lo proverò anche su PC e ti farò sapere grazie
> 
> android version is branch, no create log on 

> > Allora lo proverò anche su PC e ti farò sapere grazie
> 
> android version is branch, no create log on android

May I ask when will there be a new version for android?

**Comment by Croden1999** [comment]
> May I ask when will there be a new version for android?

waiting for Mr. Macdu

**Comment by Mizzuman** [comment]
> > May I ask when will there be a new version for android?
> 
> waiting for Mr. Macdu

I'm installing Vita3k for PC after you tell you if the game works

**Comment by Mizzuman** [comment]
> > > May I ask when will there be a new version for android?
> > 
> > 
> > waiting for Mr. Macdu
> 
> I'm installing Vita3k for PC after you tell you if the game works
hello I tried Football Manager Classic 2014 for Psvita3k on PC and it has the same problem as Android i.e. the game starts and crashes immediately so it's an "intro" and not in the game.
