### ISSUE TITLE
Hyperdimension Neptunia PP [PCSE00400]

### ISSUE THREAD

**Issue by pupilplay** [Vita3K/compatibility#1417]
Hyperdimension Neptunia PP [PCSE00400]

# App summary
- App name: Hyperdimension Neptunia PP
- App serial: PCSE00400
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3071
- Commit hash: https://github.com/vita3k/vita3k/commit/6b2a976a
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: pupilplay
- OS: Windows 10
- CPU: Intel i5-9400F
- GPU: NVIDIA GeForce GTX 1050 Ti
- RAM: 16 GB

# Issues
In the "Viewer" Mode, the character only displays for a instant and disappears soon.

# Screenshots
![issue2](https://user-images.githubusercontent.com/107766873/230721333-607b9374-313e-4da8-b13f-4d78cc06154f.jpg)
![Issue1](https://user-images.githubusercontent.com/107766873/230721329-fbc565dc-e43e-48e4-92b8-0f77d5114924.jpg)

(![](https://?))

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11183273/vita3k.log)

# Recommended labels

- Ingame +
- graphics bug

**Comment by nishinji** [comment]
already exist
https://github.com/Vita3K/compatibility/issues/454
