### ISSUE TITLE
Uncharted: Golden Abyss™ [PCSA00029]

### ISSUE THREAD

**Issue by B3TT3RS2** [Vita3K/compatibility#1423]
# App summary
- App name: Uncharted: Golden Abyss™
- App serial: PCSA00029
- App version: 1.00

# Vita3K summary
- Version: v4.0
- Build number: 4
- Commit hash: https://github.com/vita3k/vita3k/commit/8b13982b
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: B3TT3RS2
- OS: ANDROID
- CPU: SNAPDRAGON 730
- GPU: ADRENO 618
- RAM: 6 GB

# Issues
-in some moments the game lag

# Log
-the game runs between (16-30 FPS)

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
compat report submit not for Android, some games are different with pc
