### ISSUE TITLE
Hyperdimension Neptunia Re;Birth3 [PCSE00661]

### ISSUE THREAD

**Issue by BeLnep** [Vita3K/compatibility#1438]
# App summary
- App name: Hyperdimension Neptunia Re;Birth3
- App serial: PCSE00661
- App version: 1.00

# Vita3K summary
- Version: Android Release 4
- CPU backend: Dynarmic
- GPU backend: Vulkan
- Driver: 615.50
- Memory Mapping: Enabled

# Test environment summary
- Tested by: BeL#7319 (Discord)
- Device: Xiaomi Redmi 10C (MIUI Global 13.0.4)
- OS: Android 11
- CPU: Qualcomm SM6225 Snapdragon 680 4G (6 nm)
- GPU: Adreno 610
- RAM: 4 GB

# Issues
Games runs fine with memory mapping enabled, and terrible with memory mapping disabled.
Audio quality is a little bad
The rest issue is the same as Re;Birth1, Re;Birth2, and Neptune vs Sega Hard Girls.

# Screenshots
![Screenshot_2023-04-03-06-01-47-213_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662781-35684698-75ad-4f31-85be-a438279827db.jpg)
![Screenshot_2023-04-03-06-05-01-352_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662793-03bc4c02-c11b-4d03-be28-70517e369abb.jpg)
![Screenshot_2023-04-03-06-05-19-653_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662807-d0b95414-e98b-4268-9b18-aabad607199f.jpg)
![Screenshot_2023-04-03-06-07-13-756_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662817-23c53b50-04a8-4302-ae1f-376598b16c1f.jpg)
![Screenshot_2023-04-03-06-11-01-636_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662831-b2cffbf6-f4f4-4652-b5f0-edfe283b89f1.jpg)
![Screenshot_2023-04-03-06-11-46-721_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662869-20f41699-6284-4d85-9267-86b07698b288.jpg)
![Screenshot_2023-04-03-06-26-59-361_org vita3k emulator](https://user-images.githubusercontent.com/98310665/232662879-36275a30-6151-449b-a3bd-d5fdeabb78a8.jpg)

# Recommended labels
- Audio Quality
- Graphics Bug

**Comment by nishinji** [comment]
this repo is not for android
