### ISSUE TITLE
Superdimension Neptune vs Sega Hard Girls [PCSE00898]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1440]
# Vita3K summary
- Version: v0.1.6
- Build number: 3107
- Commit hash: https://github.com/vita3k/vita3k/commit/18b85823
- CPU backend: Dynarmic
- GPU backend: Vulkan

# App summary
-# App summary
- App name: Superdimension Neptune vs Sega Hard Girls
- App serial: PCSE00898
- App version: 1.00

# Test environment summary
- Tested by: tasle1001
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: AMD Ryzen 5 5500U
- GPU: Radeon Graphics
- RAM: 8GB

# Issues
shader bug, normal speed

# Screenshots
![螢幕擷取畫面 (4)](https://user-images.githubusercontent.com/131510427/233765305-04a766d9-59bc-476e-b630-11c628ca6600.png)
# Log

# Recommended labels

https://github.com/Vita3K/compatibility/labels/Playable
https://github.com/Vita3K/compatibility/labels/graphics%20bug

**Comment by nishinji** [comment]
same issue https://github.com/Vita3K/compatibility/issues/207
