### ISSUE TITLE
HELLDIVERS™ [PCSA00134]

### ISSUE THREAD

**Issue by Gonckzilla** [Vita3K/compatibility#1444]
# App summary
- App name: HELLDIVERS™
- App serial: PCSA00134
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3081
- Commit hash: https://github.com/vita3k/vita3k/commit/8b13982b
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- OS: Android 13
- CPU: Snapdragon 888
- GPU: Adreno 660
- RAM: 8GB

# Issues
Game doesn't boot. No updates installed. Tried Turnip, v615 and default drivers. Also tried with and without memory mapping.

**Comment by Croden1999** [comment]
compat report not for Android, is test different on pc version
