### ISSUE TITLE
diabolik lovers[PCSG00826] can display start sceen image but crashes while click the start button

### ISSUE THREAD

**Issue by 12345678909876543** [Vita3K/compatibility#1448]
diabolik lovers lunatic parade [PCSG00826]

# App summary
- App name: Diabolik Lovers: Lunatic Parade
- App serial: PCSG00826
- App version: 1.0

# Vita3K summary
- Version: v1.0.6
- Build number: 3126
- Commit hash: https://github.com/vita3k/vita3k/commit/9a529b2c
- CPU backend: Dynamic

# Test environment summary
- Tested by: 12345678909876543
- OS: Windows 11
- CPU: 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
- GPU: NVIDIA GeForce RTX 3070 Ti Laptop GPU
- RAM: 32 GB

# Issues
Can display start sceen image but crashes. While click the start button, the simulator shows "please wait, loading" then the program is not responding and closes instantly.
|C| [logging : : exception_handler] : Exception EXCEPTION_ACCESS_VIOLATION (0xc0000005)
|C| [logging : : exception_handler] : Read violation at adress 0x4

# Screenshots
![QQ截图20230502212508](https://user-images.githubusercontent.com/110444905/235679608-d578d84e-1fa5-4e73-8a83-4ef82f8b50dc.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11373587/vita3k.log)

# Recommended labels
- Intro
- crash

**Comment by Zangetsu38** [comment]
issue already exist #660

**Comment by 12345678909876543** [comment]
> 问题已存在 #660

The other side can run but I can't run. What does the other side's issue do for me?
