### ISSUE TITLE
Injustice: Gods Among Us Ultimate Edition [PCSE00271]

### ISSUE THREAD

**Issue by Agent-Egor** [Vita3K/compatibility#1449]
# App summary
- App name: Injustice: Gods Among Us Ultimate Edition
- App serial: PCSE00271
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Agent -Egor
- OS: Android 
- RAM: 10 Gb

# Issues
Strong graphical artifacts that interfere with the game, lags and stops when loading a battle and performing special moves.

#1088 

# Recommended labels

- In Game-

**Comment by Zangetsu38** [comment]
Invlalid, only report pc version.

**Comment by Frost-ice-gg** [comment]
Where the file
