### ISSUE TITLE
Call of Duty® Black Ops: Declassified (рус) [PCSB00232]

### ISSUE THREAD

**Issue by deividariel0909** [Vita3K/compatibility#1450]
# App summary
- App name: Call of Duty® Black Ops: Declassified (рус)
- App serial: PCSB00232
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Android Lg g7thinq android 9
- CPU: snapdragon
- GPU: adreno 630
- RAM: 4 GB

# Issues

# Screenshots
(
![Capture+_2023-05-04-06-45-22](https://user-images.githubusercontent.com/71849148/236171675-e0df3c3b-25ec-4a56-8a42-dbd045702d95.png)

# Log

# Recommended labels

- A?
- [[B?]](url)
- C?

**Comment by nishinji** [comment]
Not for Android
