### ISSUE TITLE
Trillion: God of Destruction [PCSE00813]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1451]
# App summary
- App name: Trillion: God of Destruction
- App serial: PCSE00813
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3129
- Commit hash: https://github.com/vita3k/vita3k/commit/e9969a11
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Sam 
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon(TM) Graphics
- RAM: 6 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

-[audio missing](https://github.com/Vita3K/compatibility/labels/audio%20missing)
-[Ingame +](https://github.com/Vita3K/compatibility/labels/Ingame%20%2B)
- C?

**Comment by Croden1999** [comment]
need more details
