### ISSUE TITLE
Digimon Story: Cyber Sleuth - Hacker's Memory [PCSE01171]

### ISSUE THREAD

**Issue by Shengg32** [Vita3K/compatibility#1452]
# App summary
- App name: Digimon Story: Cyber Sleuth - Hacker's Memory
- App serial: PCSE01171
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 7 GB

# Issues

# Screenshots
![image](https://?) 

# Log

# Recommended labels

- A?  Can go thru ingame
- B?
- C?

**Comment by Croden1999** [comment]
not for Android😥

**Comment by doragantenG1** [comment]
please fix the grapich isue
