### ISSUE TITLE
Shinsouban Heart no Kuni no Alice/Alice in the Country of Hearts [PCSG00614]

### ISSUE THREAD

**Issue by 12345678909876543** [Vita3K/compatibility#1454]
Shinsouban Heart no Kuni no Alice/Alice in the Country of Hearts [PCSG00614]

# App summary
- App name: Shinsouban Heart no Kuni no Alice
- App serial: PCSG00614
- App version: v1.0

# Vita3K summary
- Version: v1.0.6
- Build number: 3135
- Commit hash: https://github.com/vita3k/vita3k/commit/c4dfbf53 
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: 12345678909876543
- OS: Windows 11
- CPU: 12th Gen Intel(R) Core(TM) i7-12700H 2.30 GHz
- GPU: NVIDIA GeForce RTX 3070 Ti Laptop GPU
- RAM: 32 GB

# Issues
Can display start sceen image but crashes. While click the start button, the simulator shows "please wait, loading" then the program is not responding. The console keeps reporting errors.

# Screenshots
![QQ截图20230506155421](https://user-images.githubusercontent.com/110444905/236611297-e3616a52-d6b1-45c4-9974-2a46205be6dc.png)
![QQ截图20230506155429](https://user-images.githubusercontent.com/110444905/236611302-cbdd4115-c7be-4daa-a684-04d06a7e2fd0.png)
# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11411840/vita3k.log)

# Recommended labels

- crash
- Menu
- Intro

**Comment by Zangetsu38** [comment]
Menu + Intro ? here your gaame is just noting

**Comment by 12345678909876543** [comment]
> Menu + Intro ? here your gaame is just noting

thx I appreciate it for changing my labels into correct catagories.

**Comment by bookmist** [comment]
One of log lines
> [15:54:06.259] |C| [load_self]: You're trying to load a vitamin dump. It is not supported.

**Comment by nishinji** [comment]
This report is inaccurate

**Comment by arespade** [comment]
> This report is inaccurate

May I know why is it inaccurate? I am getting the same error too even with nonpdrm.

**Comment by bookmist** [comment]
> > This report is inaccurate
> 
> May I know why is it inaccurate? I am getting the same error too even with nonpdrm.

Could you attach vita3k.log ?

**Comment by arespade** [comment]
> > > This report is inaccurate
> > 
> > 
> > May I know why is it inaccurate? I am getting the same error too even with nonpdrm.
> 
> Could you attach vita3k.log ?

Sure, here it is.
[vita3k.log](https://github.com/Vita3K/compatibility/files/11918942/vita3k.log)

**Comment by nishinji** [comment]
> > > > This report is inaccurate
> > > 
> > > 
> > > May I know why is it inaccurate? I am getting the same error too even with nonpdrm.
> > 
> > 
> > Could you attach vita3k.log ?
> 
> Sure, here it is. [vita3k.log](https://github.com/Vita3K/compatibility/files/11918942/vita3k.log)

fuck. it is vitamin dump
vitamin modifies the eboot to make it unbootable

**Comment by arespade** [comment]
Wouldn't a vitamin dump refuse to install in the first place? I had one for the same game and I couldn't get it to install on Vita3K.

**Comment by nishinji** [comment]
Actually vitamin dump can be installed 😕
And why you don't know your game is vitamin dump?
Log cleary said
> [01:02:30.899] |C| [load_self]: You're trying to load a vitamin dump. It is not supported.
