### ISSUE TITLE
Ragnarok Odyssey ACE [PCSE00300]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1458]
# App summary
- App name: Ragnarok Odyssey ACE
- App serial: PCSE00300
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3135
- Commit hash: https://github.com/vita3k/vita3k/commit/c4dfbf53
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics
- RAM: 6GB

# Issues

# Screenshots
![螢幕擷取畫面 (9)](https://user-images.githubusercontent.com/131510427/236630331-52c3f9bc-68f1-4fbd-a72e-f48a61d35ffb.png)
![螢幕擷取畫面 (10)](https://user-images.githubusercontent.com/131510427/236630353-07296b04-5df6-4aa1-8dcc-ba634166db3c.png)

# Log

# Recommended labels

 [Ingame -](https://github.com/Vita3K/compatibility/labels/Ingame%20-)
[graphics bug](https://github.com/Vita3K/compatibility/labels/graphics%20bug)
- C?

**Comment by Croden1999** [comment]
this issue report is duplicate issue, look https://github.com/Vita3K/compatibility/issues/851

**Comment by Zangetsu38** [comment]
yes, i have no see lol, thx log
