### ISSUE TITLE
Persona 4: Dancing All Night [PCSB00867]

### ISSUE THREAD

**Issue by noraprime** [Vita3K/compatibility#1460]
# App summary
- App name: Persona 4: Dancing All Night
- App serial: PCSB00867
- App version: 1.00

# Vita3K summary
- Version: v0.1.6 
- Build number: 3135
- Commit hash: I don't know, I am not very experienced in this.
- CPU backend: Dynamic
- GPU backend: OpenGL

# Test environment summary
- Tested by: me
- OS: Windows 10
- CPU: Intel® Core™ i5-8265U
- GPU: NVIDIA GeForce MX110
- RAM: 8 GB

# Issues
Audio Crackling only, game is playable very fine and only crackles when Sound Effects or Voices are present, when there is only music it sounds fine

# Screenshots
![Vita3K_9s4BcIial7](https://user-images.githubusercontent.com/130231606/236641095-43542c11-2b75-418b-bc5c-9051899c9adb.png)
![Vita3K_mpNHSLezR4](https://user-images.githubusercontent.com/130231606/236641102-e9ce0896-d7cf-4f5d-a427-d25c701eabb9.png)
![Vita3K_srdcjuKexM](https://user-images.githubusercontent.com/130231606/236641112-d701d234-c5e0-4c33-9c12-4652dfc83aac.png)
![Vita3K_Q0TEBdUmRc](https://user-images.githubusercontent.com/130231606/236641117-3b34a2df-3658-4320-b85f-be19d582a073.png)
![Vita3K_iFbbb16Gv8](https://user-images.githubusercontent.com/130231606/236641124-688200fe-69b5-4c1b-b545-c5cdc6adf4b4.png)
![Vita3K_hNosmc2FF0](https://user-images.githubusercontent.com/130231606/236641128-c2ba5b00-e16e-4054-8fb6-53ea41f68d5f.png)
![Vita3K_GPhzN0nIax](https://user-images.githubusercontent.com/130231606/236641136-9c3b58e7-9596-48ec-950e-04aaa2c6a736.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11413117/vita3k.log)

# Recommended labels

- Playable
- audio quality
- outdated

**Comment by Zangetsu38** [comment]
why oudated  ?

**Comment by Zangetsu38** [comment]
issue already exist
https://github.com/Vita3K/compatibility/issues/1168

**Comment by noraprime** [comment]
> issue already exist #1168



> why oudated ?

It's just that I feel like it is playable (Like Persona 3 Dancing), while it's marked as IG+
I apologize if it was unnecesary and a waste of time
