### ISSUE TITLE
MOBILE SUIT GUNDAM EXTREME VS-FORCE [PCSH00195]

### ISSUE THREAD

**Issue by Rekkusu09** [Vita3K/compatibility#1465]
# App summary
- App name: MOBILE SUIT GUNDAM EXTREME VS-FORCE
- App serial: PCSH00195
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 5 GB

# Issues
 Menu Shows well. But during ingame battlefield.. graphics went down. 

# Screenshots
![image](https://?)
![Screenshot_20230511-121944](https://github.com/Vita3K/compatibility/assets/133083456/78e22824-29a6-4657-b5e4-6cea9cd0c8ad)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Rekkusu09** [comment]
I wanna hope this gets improvement soon with tht new build of vita3k

**Comment by nishinji** [comment]
this repo not for android
