### ISSUE TITLE
Ragnarok Odyssey ACE [PCSE00300]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1470]
# App summary
- App name: Ragnarok Odyssey ACE
- App serial: PCSE00300
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3157
- Commit hash: https://github.com/vita3k/vita3k/commit/4280bea5
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics
- RAM: 6GB

# Issues

# Screenshots
![螢幕擷取畫面 (9)](https://github.com/Vita3K/compatibility/assets/131510427/c567b4ea-86ad-465e-ac99-f9c9bbde3f83)
![螢幕擷取畫面 (10)](https://github.com/Vita3K/compatibility/assets/131510427/0b352cfa-5ce8-492b-a104-364c344c9c16)

# Log
![螢幕擷取畫面 (11)](https://github.com/Vita3K/compatibility/assets/131510427/5376b4f3-f3ca-497d-9a9b-8758df47d28c)

# Recommended labels

- [graphics bug](https://github.com/Vita3K/compatibility/labels/graphics%20bug)
- [Ingame -](https://github.com/Vita3K/compatibility/labels/Ingame%20-)
- C?

**Comment by nishinji** [comment]
#851
