### ISSUE TITLE
Chronovolt [PCSE00044]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1496]
# App summary
- App name: Chronovolt
- App serial: PCSE00044
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3162
- Commit hash: https://github.com/vita3k/vita3k/commit/3abd4e36
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics 
- RAM: 6 GB

# Issues
Have sound, normal speed 

# Screenshots
![螢幕擷取畫面 (52)](https://github.com/Vita3K/compatibility/assets/131510427/f31d5f33-5b8a-4565-a438-053484cbf8fe)
![螢幕擷取畫面 (53)](https://github.com/Vita3K/compatibility/assets/131510427/0dd4b143-c516-4ec9-a04b-444cdcbb959a)

# Log
![螢幕擷取畫面 (54)](https://github.com/Vita3K/compatibility/assets/131510427/23cf62f1-c7a7-49c0-bc6e-0bb5e1ca398a)

# Recommended labels

-[crash](https://github.com/Vita3K/compatibility/labels/crash)
- B?
- C?

**Comment by Croden1999** [comment]
duplicate issue, check to #24
