### ISSUE TITLE
Doctor Who: The Eternity Clock [PCSE00103]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1509]
# App summary
- App name: Doctor Who: The Eternity Clock
- App serial: PCSE00103
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3164
- Commit hash: https://github.com/vita3k/vita3k/commit/c453f24c
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics
- RAM: 6GB

# Issues

# Screenshots
![螢幕擷取畫面 (82)](https://github.com/Vita3K/compatibility/assets/131510427/45f8cbea-35cd-450d-9b2f-5ee18a488fb3)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11517731/vita3k.log)

# Recommended labels

[Ingame -](https://github.com/Vita3K/compatibility/labels/Ingame%20-)
-[graphics bug](https://github.com/Vita3K/compatibility/labels/graphics%20bug)
- C?

**Comment by Croden1999** [comment]
you submit twice.issue.
