### ISSUE TITLE
DYNASTY WARRIORS NEXT [PCSE00014]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1511]
# App summary
- App name: DYNASTY WARRIORS NEXT
- App serial: PCSE00014
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3164
- Commit hash: https://github.com/vita3k/vita3k/commit/c453f24c
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics
- RAM: 6GB

# Issues

# Screenshots
![螢幕擷取畫面 (85)](https://github.com/Vita3K/compatibility/assets/131510427/dcbb5630-263b-44c3-b277-e1b13e1e9698)
![螢幕擷取畫面 (86)](https://github.com/Vita3K/compatibility/assets/131510427/b438bcfc-846c-48b0-ae69-dee18c61e709)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11518021/vita3k.log)

# Recommended labels

-[Playable](https://github.com/Vita3K/compatibility/labels/Playable)
- B?
- C?

**Comment by Croden1999** [comment]
duplicate issue
see https://github.com/Vita3K/compatibility/issues/728
