### ISSUE TITLE
Dragon Fin Soup [PCSE00447]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1515]
# App summary
- App name: Dragon Fin Soup
- App serial: PCSE00447
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3164
- Commit hash: https://github.com/vita3k/vita3k/commit/c453f24c
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Sam 
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD  Radeon Graphics 
- RAM: 6 GB

# Issues

# Screenshots
![螢幕擷取畫面 (90)](https://github.com/Vita3K/compatibility/assets/131510427/02b24aed-27f9-4931-8789-13f8abff7f96)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11522464/vita3k.log)

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
no create double issue for same game
