### ISSUE TITLE
DYNASTY WARRIORS NEXT [PCSE00014]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1530]
# App summary
- App name: DYNASTY WARRIORS NEXT
- App serial: PCSE00014
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3174
- Commit hash: https://github.com/vita3k/vita3k/commit/95ac0805
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics       
- RAM: 6GB

# Issues

# Screenshots
![螢幕擷取畫面 (102)](https://github.com/Vita3K/compatibility/assets/131510427/2d6b2f8a-0030-44e1-8822-f75b1c37acc6)
![螢幕擷取畫面 (103)](https://github.com/Vita3K/compatibility/assets/131510427/75a33a50-c8dc-4045-a379-59cf588f5f53)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11571395/vita3k.log)

# Recommended labels

- [Ingame +](https://github.com/Vita3K/compatibility/labels/Ingame%20%2B)
-[crash](https://github.com/Vita3K/compatibility/labels/crash)
- C?

**Comment by Croden1999** [comment]
duplicate issue
see https://github.com/Vita3K/compatibility/issues/728
