### ISSUE TITLE
GOD EATER 2 RAGE BURST [PCSE00789]

### ISSUE THREAD

**Issue by tasle1001** [Vita3K/compatibility#1534]
# App summary
- App name: GOD EATER 2 RAGE BURST
- App serial: PCSE00789
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3178
- Commit hash: https://github.com/vita3k/vita3k/commit/dd4a96f8
- CPU backend: Unicorn
- GPU backend: Vulkan

# Test environment summary
- Tested by: sam
- OS: Windows 10
- CPU: AMD 5500u
- GPU: AMD Radeon Graphics      
- RAM: 6GB

# Issues
no sound, slow
# Screenshots
![螢幕擷取畫面 (104)](https://github.com/Vita3K/compatibility/assets/131510427/5ddaccec-9c66-4747-8852-facbceaf1d9e)
![螢幕擷取畫面 (105)](https://github.com/Vita3K/compatibility/assets/131510427/4a5c49ba-8ac7-4a8b-8bce-e223aef00798)
![螢幕擷取畫面 (106)](https://github.com/Vita3K/compatibility/assets/131510427/46ca63c3-1c14-4775-9798-6039749bbf63)
![螢幕擷取畫面 (107)](https://github.com/Vita3K/compatibility/assets/131510427/9614cca4-fb1d-4db4-800c-59eb3b5ab2e3)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11580937/vita3k.log)

# Recommended labels

- [Ingame -](https://github.com/Vita3K/compatibility/labels/Ingame%20-)
-[crash](https://github.com/Vita3K/compatibility/labels/crash)
- [audio missing](https://github.com/Vita3K/compatibility/labels/audio%20missing)

**Comment by Croden1999** [comment]
should be menu, not ingame
