### ISSUE TITLE
Ridge Racing [PCSB00048] 

### ISSUE THREAD

**Issue by SRLSPEED** [Vita3K/compatibility#1542]
# App summary
- App name: Ridge Racer
- App serial: PCSB00048
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3182
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: Dynamic
- GPU backend: VuIkan

# Test environment summary
- Tested by: speed
- Operating System: Windows 11
- CPU: Intel i3-1115G4
- GPU:  Intel Core Monitor
- RAM: 8GB

# Issues
There is a certain probability of errors when loanding into the game hall. The code is stuck and flashing, which has been quite busy recently

# Screenshots
(https://github.com/Vita3K/compatibility/assets/130912334/9043d2c1-5b2f-4e9a-a18f-e69d02825b61)

# Log 

[vita3k.log](https://github.com/Vita3K/compatibility/files/11582570/vita3k.log) 

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
issue already exist
