### ISSUE TITLE
ONE PIECE: PIRATE WARRIORS 3 [PCSE00638]

### ISSUE THREAD

**Issue by persickboy** [Vita3K/compatibility#1548]
# App summary
- App name: ONE PIECE: PIRATE WARRIORS 3
- App serial: PCSE00638
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 7 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by othmanead** [comment]
closing as not enough information
