### ISSUE TITLE
Gakuen K - Wonderful School Days V Edition [PCSG00654]

### ISSUE THREAD

**Issue by Dystnine** [Vita3K/compatibility#1592]
# App summary
- App name: 学園K -Wonderful School Days- V  Edition
- App serial: PCSG00654
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3173
- Commit hash: https://github.com/vita3k/vita3k/commit/42d6b4ef
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: Dystnine
- OS: Windows 7
- CPU: INTEL I3 4100U
- GPU: AMD HD8500M
- RAM: 8 GB

# Issues

The emulator will freeze when loading.
# Screenshots
![27](https://github.com/Vita3K/compatibility/assets/123282693/d78b1cb2-eabd-41fd-b978-d8539fb28621)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11642694/vita3k.log)

# Recommended labels

Menu

**Comment by bookmist** [comment]
>[load_self]: You're trying to load a vitamin dump. It is not supported.
