### ISSUE TITLE
Yomawari: Night Alone [PCSE00909]

### ISSUE THREAD

**Issue by Jyazue** [Vita3K/compatibility#1645]
# App summary
- App name: Yomawari: Night Alone
- App serial: PCSE00909
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3226
- Commit hash: https://github.com/vita3k/vita3k/commit/10641e59
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Jyazue
- OS: Android 13
- CPU: Mediatek Helio G95
- GPU: Mali G7
- RAM: 8 GB

# Issues
Game works fine. It boots, and is playable. Saving game data at the house however, does not work.

# Screenshots

# Log

# Recommended labels
-savedata bug
-ingame+

**Comment by nishinji** [comment]
this repo is not for android
