### ISSUE TITLE
Ratchet & Clank Collection™ [PCSA00133]

### ISSUE THREAD

**Issue by Gerold55** [Vita3K/compatibility#1649]
# App summary
- App name: Ratchet & Clank Collection™
- App serial: PCSA00133
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3209
- Commit hash: https://github.com/vita3k/vita3k/commit/22ea4f03
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Gerold55
- OS: Windows 11
- CPU: Intel Core i5 9300H
- GPU: NVIDIA Geforce GTX 1650
- RAM: 8 GB

# Issues
Crashes occasionally

# Screenshots
![Screenshot 2023-06-16 200923](https://github.com/Vita3K/compatibility/assets/13843095/993523cd-0fc8-4647-a92c-afdb2dd647bb)
![Screenshot 2023-06-16 200948](https://github.com/Vita3K/compatibility/assets/13843095/4dc9cbe7-202a-4591-8282-d61dcaca5604)
![Screenshot 2023-06-16 200851](https://github.com/Vita3K/compatibility/assets/13843095/f6420013-be13-40a2-bf0b-cab850c07406)

# Log
[vita3k - Copy.log](https://github.com/Vita3K/compatibility/files/11777294/vita3k.-.Copy.log)

# Recommended labels
- Ingame -

**Comment by ArbestRiAgain** [comment]
OpenGL doesn't crash

**Comment by othmanead** [comment]
@Gerold55 try with opengl as the comment said and report again

**Comment by nishinji** [comment]
Closed due to questionable report content.
