### ISSUE TITLE
Fate/EXTELLA LINK [PCSE01254]

### ISSUE THREAD

**Issue by Jansen121** [Vita3K/compatibility#1650]
# App summary
- App name: Fate/Extella LINK
- App serial: PCSE01254
- App version: 1.00

# Vita3K summary
- Version: v6
- GPU backend: Vulkan

# Test environment summary
- Tested by: Jansen121
- OS: Jansen121
- CPU: Snapdragon 888+
- GPU: Adreno 660
- RAM: 8 GB

# Issues
Playable with menu bg bug and stuttering audio.

# Screenshots
![Screenshot_20230616-215955](https://github.com/Vita3K/compatibility/assets/131414657/34d0b51d-882d-4878-8c11-217699fcd482)

# Log

# Recommended labels

- Playable
- Menu bug
- Audio crackling

**Comment by othmanead** [comment]
we can't accept android reports in this repository
