### ISSUE TITLE
Shiro to Kuro no Alice -Twilight line-[PCSG01192]

### ISSUE THREAD

**Issue by Dystnine** [Vita3K/compatibility#1656]
# App summary
- App name: 白と黒のアリス -Twilight line-
- App serial: PCSG01192
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3209
- Commit hash: https://github.com/vita3k/vita3k/commit/22ea4f03
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Dystnine
- OS: Windows 7
- CPU: INTEL I3 4100U
- GPU: AMD HD8500M
- RAM: 8 GB

# Issues

Everything is works.

# Screenshots
![图片](https://github.com/Vita3K/compatibility/assets/123282693/0ef68e8c-2aa5-47a9-80ff-66f11ee59c7d)
![图片](https://github.com/Vita3K/compatibility/assets/123282693/8c04e145-74eb-4f0c-88e9-a2a1e5275eb9)
![图片](https://github.com/Vita3K/compatibility/assets/123282693/5b5710d7-b120-4153-9144-1cfdcf29364a)
![图片](https://github.com/Vita3K/compatibility/assets/123282693/5b314790-66d4-4942-9d8d-09a0e021e46b)
![图片](https://github.com/Vita3K/compatibility/assets/123282693/d0157336-57b6-485c-b581-6ecc9b0766a4)
![图片](https://github.com/Vita3K/compatibility/assets/123282693/f552ebfc-a8ef-4bb2-8915-ae6235c2c073)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11778659/vita3k.log)

# Recommended labels

Playable

**Comment by othmanead** [comment]
duplicate from https://github.com/Vita3K/compatibility/issues/1652
