### ISSUE TITLE
LittleBigPlanet PS Vita [PCSA00017]

### ISSUE THREAD

**Issue by sh0u1** [Vita3K/compatibility#167]
# Game summary
- Game name: LittleBigPlanet PS Vita
- Game serial: PCSA00017

# Vita3K summary
- Version: v0.1
- Build number: 741-f506355
- Commit hash: https://github.com/Vita3K/Vita3K/commit/f506355364bd78d62bc681e471cb77a81e898da4

# Test environment summary
- Tested by: sh0u1
- OS: Windows 8.1 64-bit
- CPU: Intel i3-4030U 
- GPU: Intel HD Graphics 4400 (Mobile 1.0/1.1Ghz)
- RAM: 8 GB

# Issues

crash

# Screenshots
[Screenshot-68.png](https://i.ibb.co/fMJjb11/Screenshot-68.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/2898474/vita3k.log)
# Recommended labels
- Crash

**Comment by VelocityRa** [comment]
Vitamin dumps are unsupported, either close this or re-test with a Maidump (or Maidump + FAGDec `eboot.bin`) dump.
