### ISSUE TITLE
Bloodstained: Curse of the Moon [PCSE01262]

### ISSUE THREAD

**Issue by hussein3t** [Vita3K/compatibility#1673]
# App summary
- App name: Bloodstained: Curse of the Moon
- App serial: PCSE01262
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3226
- Commit hash: https://github.com/vita3k/vita3k/commit/10641e59
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Hussein
- OS: Android 13
- CPU: Snapdragon 732g
- GPU: Adreno 618
- RAM: 8gb

# Issues

-Game Goes in-game
-has few visual bugs
-flickering when seeing new areas
-Random slowdowns lasts for 1-2s
-Stable performance ( except the random slowdowns )

# Screenshots
!
![Screenshot_2023-06-20-13-30-13-997_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/73926628/51542bee-0282-44fe-8579-a3b9a9666427)
![Screenshot_2023-06-20-13-29-47-434_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/73926628/66273acb-af80-47c8-9417-51a696c6fc80)

# Log

# Recommended labels

- A- in-game 
- B- visual bugs 
- C- stable performance

**Comment by nishinji** [comment]
this repo is not for android
