### ISSUE TITLE
METAL MAX Xeno [PCSH10100]

### ISSUE THREAD

**Issue by gbqgbq** [Vita3K/compatibility#1716]
# App summary
- App name: METAL MAX Xeno
- App serial: PCSH10100
- App version: 1.01

# Vita3K summary
- Version: v0.1.8
- Build number: 3228
- Commit hash: https://github.com/vita3k/vita3k/commit/12224d7c
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: gbq 
- OS: Windows 11 22H2/
- CPU: Intel 12700
- GPU: NVIDIA 3060 TI
- RAM: 16 GB

Playable, however, there is a slight error in the image at the beginning of the game, and most of the image is normal

**Comment by othmanead** [comment]
please include screenshots and a log
