### ISSUE TITLE
Utawarerumono: Mask of Truth [PCSE01102]

### ISSUE THREAD

**Issue by AxeYou** [Vita3K/compatibility#172]
# Game summary
- Game name: Utawarerumono: Mask of Truth
- Game serial: [PCSE01102]

# Vita3K summary
- Version: v0.1
- Build number: 844
- Commit hash: https://github.com/vita3k/vita3k/commit/89fb97b

# Test environment summary
- Tested by: AxeYou
- OS: Windows 7
- CPU: Intel Pentium G630 @2.70GHz
- GPU: AMD Radeon HD 5700 Series
- RAM: 8 GB

# Issues
Game won't boot/load after instalation by the emulator.

> [23:24:11.216] |C| [load_self]: SELF app0:sce_module/libc.suprx is corrupt or encrypted. Decryption is not yet supported.

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/3000938/vita3k.log)

**Comment by IllusionMan1212** [comment]
Encrypted game
