### ISSUE TITLE
DYING: Reborn [PCSE00984]

### ISSUE THREAD

**Issue by Mark-kun** [Vita3K/compatibility#1900]
# App summary
- App name: DYING: Reborn
- App serial: PCSE00984
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3226
- Commit hash: https://github.com/vita3k/vita3k/commit/10641e59
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by:mark-kun
- OS: android
- CPU: Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55) (mediatek Helio g80)
- GPU: Mali g52
- RAM: 3 GB

# Issues
Slightly fps drop

# Screenshots
![image](https://?)

Playable
60 fps in start screen and 30 fps on game
I think it will go up to 60 fps if your device was power enough 
![Screenshot_2023-06-30-17-27-39-46_74fe318baca9186e0035f53f6dd1d3fc](https://github.com/Vita3K/compatibility/assets/138265604/df6efbb6-f716-41dc-a5d6-18ab3fc38daa)
![Screenshot_2023-06-30-17-27-14-54_74fe318baca9186e0035f53f6dd1d3fc](https://github.com/Vita3K/compatibility/assets/138265604/7d66922e-ba3d-47a1-afe2-1df56522ce00)
![Screenshot_2023-06-30-17-27-01-94_74fe318baca9186e0035f53f6dd1d3fc](https://github.com/Vita3K/compatibility/assets/138265604/d0f85638-c5b1-4b29-ac03-b2d5f8cb658d)
![Screenshot_2023-06-30-17-26-01-19_74fe318baca9186e0035f53f6dd1d3fc](https://github.com/Vita3K/compatibility/assets/138265604/67ae3e70-8219-4388-ae43-5457ae3641b7)
![Screenshot_2023-06-30-17-25-20-45_74fe318baca9186e0035f53f6dd1d3fc](https://github.com/Vita3K/compatibility/assets/138265604/831d5225-411f-443b-be36-228bd11c89f4)

**Comment by othmanead** [comment]
this repository is only for testing the pc version
