### ISSUE TITLE
Phantasy Star Nova [PCSH00143]

### ISSUE THREAD

**Issue by jiuyuan1995** [Vita3K/compatibility#1914]
# App summary
- App name: Phantasy Star Nova (夢幻之星 NOVA)
- App serial: PCSH00143
- App version: 1.01
# Vita3K summary
- Version: v0.1.8
- Build number: 3249
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

# Test environment summary
- Tested by: Croden1999
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: Intel I9
- GPU: NVIDIA 3070
- RAM: 32G

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by jiuyuan1995** [comment]
The game font display is normal

Unable to enter the game due to stuck character creation interface.

We really want to play this game!!!!!!!!!!!!!!

Thank you all for your hard work!!!!!!! Hope to repair it soon!

**Comment by Croden1999** [comment]
duplicate and invalid report, see https://github.com/Vita3K/compatibility/issues/1218
重复及无效报告，请浏览https://github.com/Vita3K/compatibility/issues/1218
