### ISSUE TITLE
Need For Speed™ Most Wanted [PCSB00183]

### ISSUE THREAD

**Issue by Daniperher13** [Vita3K/compatibility#1939]
# App summary
- App name: Need For Speed™ Most Wanted
- App serial: PCSB00183
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3226
- Commit hash: https://github.com/vita3k/vita3k/commit/10641e59
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 5 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by othmanead** [comment]
please include screenshots and a log

**Comment by GamingDucking** [comment]
please add a screenshot, log and the labels for recommended labels
