### ISSUE TITLE
Hello Kitty to issho! Block Crash V [PCSG00059]

### ISSUE THREAD

**Issue by iluvmesomesanrio** [Vita3K/compatibility#2094]
# App summary
- App name: ハローキティといっしょ! ブロッククラッシュV
- App serial: PCSG00059
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3259
- Commit hash: https://github.com/vita3k/vita3k/commit/be74f383
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: acc 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 8 GB

# Issues

# Screenshots
https://m.media-amazon.com/images/I/51P8B+SdY6L.jpg
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by iluvmesomesanrio** [comment]
sorry this is my first time using github with a account i don't really know what all to add but the game runs perfect i just noticed that it wasn't on the compatibility list :)

**Comment by GamingDucking** [comment]
please update your screenshots and logs since you can upload to Github
