### ISSUE TITLE
英雄傳說 閃之軌跡 [PCSH00074]

### ISSUE THREAD

**Issue by colorfox** [Vita3K/compatibility#2121]
# App summary
- App name: 英雄傳說 閃之軌跡
- App serial: PCSH00074
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3265
- Commit hash: https://github.com/vita3k/vita3k/commit/fb15e955
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: wangjif 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 16 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
need more detail
需要更多详细内容
