### ISSUE TITLE
Madden 13

### ISSUE THREAD

**Issue by 9thwardRondo** [Vita3K/compatibility#2216]
Still having graphicissues it blinks with version 1 2 3 4 and 5 it made it pass the menu screen let you choose teams n start game now with version 6 its worst 

# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by ArbestRiAgain** [comment]
Invalid
