### ISSUE TITLE
Collar x Malice [PCSE01011] gameplay issue

### ISSUE THREAD

**Issue by Chizuya** [Vita3K/compatibility#2219]
I have issue while playing the game when it clearly put playable.

Device: Android/Redmi note 9
CPU: octa-core max 2.00Hz

Like please tell me if this issue already have a fix at least? I really wanted to play this🥲

![Screenshot_2023-07-20-21-22-05-282_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/140083037/8a1c2499-2b11-47eb-8e88-e7b0dbc75763)
![Screenshot_2023-07-20-21-15-40-379_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/140083037/72284c4e-91bd-4541-9148-baacdcafb4de)
![Screenshot_2023-07-20-21-14-30-909_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/140083037/cf6b9db7-05f1-4033-b573-2195fab7d22d)

**Comment by nishinji** [comment]
this repo is not for android

**Comment by Chizuya** [comment]
> this repo is not for android

If it's not for android, then at least consider making it playable for the android user😅
