### ISSUE TITLE
NINJA GAIDEN Σ PLUS [PCSG00033]

### ISSUE THREAD

**Issue by danielferreirabet** [Vita3K/compatibility#2283]
# App summary
- App name: NINJA GAIDEN Σ PLUS
- App serial: PCSG00033
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3159
- Commit hash: https://github.com/vita3k/vita3k/commit/f6ac90fb
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 3 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by ArbestRiAgain** [comment]
Invalid, user also appears to be below min. specs

**Comment by nishinji** [comment]
It's not for you to judge that
stop posting pointless comments
