### ISSUE TITLE
ラブライブ！ School idol paradise Vol.1 Printemps [PCSG00422]

### ISSUE THREAD

**Issue by Gamingdiax955** [Vita3K/compatibility#2293]
# App summary
- App name: ラブライブ！ School idol paradise Vol.1 Printemps
- App serial: PCSG00422
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3273
- Commit hash: https://github.com/vita3k/vita3k/commit/816af374
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: ?
- OS: Windows 10
- CPU: AMD Ryzen 7 5800x
- GPU: NVIDIA RTX 3070
- RAM: 16 GB

# Issues

# Screenshots
![image](https://github.com/Vita3K/compatibility/assets/44947065/c2cef153-e595-49c6-9f4c-79d8d16c380d)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
this report already exist, see #694
