### ISSUE TITLE
Danganronpa2: Goodbye Despair [PCSB00514]

### ISSUE THREAD

**Issue by chris202020202020** [Vita3K/compatibility#2302]
# App summary
- App name: Danganronpa2: Goodbye Despair
- App serial: PCSB00514
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3323
- Commit hash: https://github.com/vita3k/vita3k/commit/90255cdd
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- playable
- graphics bug
- ingame +
- vulkan issue

**Comment by Zangetsu38** [comment]
No open multiple issue for one game, update current exist
