### ISSUE TITLE
vita3k letter error on new version 7

### ISSUE THREAD

**Issue by agentxx44** [Vita3K/compatibility#2305]
# App summary
- App name:vita3k apk
- App version:version7

# Test environment summary
- Tested by: pixel 3 xl snapdragon 845)

- CPU:Octa-core (4x2.5 GHz Kryo 385 Gold & 4x1.6 GHz Kryo 385 Silver
- GPU:Adreno 630
- RAM:4gb

# Issues
the vita3k app has an error with the letters in the new version vita3k version 7 please fix it thank you look at the screen shot

# Screenshots
![Screenshot_20230814-222501](https://github.com/Vita3K/compatibility/assets/66709674/a80c771f-4de9-4b7a-ae1e-859486d737f8)

![Screenshot_20230814-222501](https://github.com/Vita3K/compatibility/assets/66709674/a80c771f-4de9-4b7a-ae1e-859486d737f8)

# Recommended labels

**Comment by ArbestRiAgain** [comment]
Invalid
