### ISSUE TITLE
Batman™: Arkham Origins Blackgate [PCSE00269]

### ISSUE THREAD

**Issue by ONENAMED** [Vita3K/compatibility#2318]
# App summary
- App name: Batman™: Arkham Origins Blackgate
- App serial: PCSE00269
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3305
- Commit hash: https://github.com/vita3k/vita3k/commit/eb28b844
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Android 13
- CPU: mediatek g95
- GPU: Mali g76
- RAM: 6 GB

# Issues

Low FPS
And
Texture glitch

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by nishinji** [comment]
lack of info
