### ISSUE TITLE
LittleBigPlanet™ PlayStation®Vita PCSF00021 1.22

### ISSUE THREAD

**Issue by Vergi314** [Vita3K/compatibility#2328]
# App summary
- App name: LittleBigPlanet™ PlayStation®Vita
- App serial: PCSF00021
- App version: 1.22

# Vita3K summary
- Version: v0.1.8
- Build number: 3335-7540bf75
- CPU backend: Dynarmic
- GPU backend:Vulkan

# Test environment summary
- Tested by: Vergi314
- OS: Windows 10
- CPU: AMD
- GPU:NVIDIA
- RAM: 4 GB

# Issues
It keeps crashing whenever attempting to play the cutscene level "The Plot Thickens!" from Jackpot City, it just freezes and crashes mid-loading when entering. The log says this error message:[12:59:47.973] |C| [logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. vk::Device::allocateDescriptorSets: ErrorOutOfPoolMemory. Could it be a potential memory leak? Anyway, i am unable to progress through story mode now because of this.

# Screenshots

# Log
[12:59:47.973] |C| [logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. vk::Device::allocateDescriptorSets: ErrorOutOfPoolMemory
# Recommended labels

- A?
- B?
- C?

**Comment by Croden1999** [comment]
your issue is duplicate, see #188
