### ISSUE TITLE
Hyperdimension Neptunia Re;Birth2 SISTERS GENERATION [PCSE00508]

### ISSUE THREAD

**Issue by kazumi371** [Vita3K/compatibility#2333]
# App summary
- App name: Hyperdimension Neptunia Re;Birth2 SISTERS GENERATION
- App serial: PCSE00508
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3338
- Commit hash: https://github.com/vita3k/vita3k/commit/44d8c5da
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: hp 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 16 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

it crashes my emulatwer

**Comment by nishinji** [comment]
lack of info
