### ISSUE TITLE
DEAD OR ALIVE 5 PLUS [PCSE00235]

### ISSUE THREAD

**Issue by YuzzYeager** [Vita3K/compatibility#2341]
# App summary
- App name: DEAD OR ALIVE 5 PLUS
- App serial: PCSE00235
- App version: 1.01

# Vita3K summary
- Version: v0.1.8
- Build number: 3305
- Commit hash: https://github.com/vita3k/vita3k/commit/eb28b844
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 5 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by YuzzYeager** [comment]
Force close when write data
![Screenshot_2023-09-16-12-46-56-307_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/145179581/54b39edd-902f-4663-bfe6-30e22536430e)
![Screenshot_2023-09-16-12-47-02-699_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/145179581/55e24910-efb1-4c18-8c1c-17b3ea767f4e)

**Comment by YuzzYeager** [comment]
![Uploading Screenshot_2023-09-16-12-50-46-590_org.vita3k.emulator.jpg…]()
![Screenshot_2023-09-16-12-50-40-386_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/145179581/05ee81dd-37ea-41c8-8e7a-4b673f4d2eb4)

**Comment by YuzzYeager** [comment]
![Uploading Screenshot_2023-09-16-12-50-40-386_org.vita3k.emulator.jpg…]()

**Comment by Croden1999** [comment]
report not support Android version
