### ISSUE TITLE
Race The Sun [PCSE00461]

### ISSUE THREAD

**Issue by Good149o8** [Vita3K/compatibility#2342]
# App summary
- App name: Race The Sun
- App serial: PCSE00461
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3305
- Commit hash: https://github.com/vita3k/vita3k/commit/eb28b844
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: 1200
- GPU: AMD/NVIDIA/Intel?
- RAM: 8 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

Reproducible

**Comment by Croden1999** [comment]
invalid report
