### ISSUE TITLE
Oreshika: Tainted Bloodlines [PCSD00084]

### ISSUE THREAD

**Issue by EngrealSun** [Vita3K/compatibility#2347]
# App summary
- App name: 俺屍２─跨越俺的屍體前進吧
- App serial: PCSD00084
- App version: 1.01

# Vita3K summary
- Version: v0.1.9
- Build number: 3420
- Commit hash: https://github.com/vita3k/vita3k/commit/6d65c2f9
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: engreal 
- OS: Windows 10 专业版 22H2
- CPU: AMD Ryzen 5 5600 6-Core Processor 3.50 GHz
- GPU: AMD Radeon RX 6650XT
- RAM: 16 GB

# Screenshots
![image](https://github.com/Vita3K/compatibility/assets/55591636/87a9d1cd-d8e6-43b2-99c5-eb056f33f83f)

# Log

# Recommended labels

- Ingame +
- camera

**Comment by EngrealSun** [comment]
![image](https://github.com/Vita3K/compatibility/assets/55591636/16ccae86-58e1-45be-b804-da8d270701aa)
[log.txt](https://github.com/Vita3K/compatibility/files/12744664/log.txt)

**Comment by nishinji** [comment]
change title to `Oreshika: Tainted Bloodlines`

**Comment by Zangetsu38** [comment]
@nishinji you can checking this game, report here is strange, euro ver is playable

**Comment by nishinji** [comment]
@EngrealSun can you retest?
euro and jpn ver is playable

**Comment by nishinji** [comment]
it seems inaccurate
