### ISSUE TITLE
![Screenshot_20231004-020641](https://github.com/Vita3K/compatibility/assets/146876496/aa44cf6b-4746-46ee-8cad-e927c388975b)

### ISSUE THREAD

**Issue by jegesim** [Vita3K/compatibility#2348]
![Screenshot_20231004-020641](https://github.com/Vita3K/compatibility/assets/146876496/aa44cf6b-4746-46ee-8cad-e927c388975b)

![Screenshot_20231004-020614](https://github.com/Vita3K/compatibility/assets/146876496/ce8e24d3-ef76-4644-b7a5-809b9ab958ff)
Now playable without noticeable glitches

_Originally posted by @jegesim in https://github.com/Vita3K/compatibility/issues/950#issuecomment-1745485340_

**Comment by Croden1999** [comment]
issue is invalid

**Comment by nishinji** [comment]
nice
