### ISSUE TITLE
STREET FIGHTER X TEKKEN [PCSG00063]

### ISSUE THREAD

**Issue by crracks** [Vita3K/compatibility#2352]
# App summary
- App name: STREET FIGHTER X TEKKEN
- App serial: PCSG00063
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 7 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by nishinji** [comment]
lack of info
