### ISSUE TITLE
SAMURAI WARRIORS 4-Ⅱ [PCSE00737]

### ISSUE THREAD

**Issue by testerforfree** [Vita3K/compatibility#2353]
# App summary
- App name: SAMURAI WARRIORS 4-Ⅱ
- App serial: PCSE00737
- App version: 1.00

# Vita3K summary
- Version: v8
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynamic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Testforfree
- OS: Android 12 Infinix Zero 5G, Dimensity 900
- CPU: Octa-core (2x2.4 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)
- GPU: Mali-G68 MC4
- RAM: 8GB

# Issues
There are some inconvenience about the ground changing colours and also the hp bar on enemy in the battlefield is missing.

# Screenshots
![Screenshot_20231007-083413](https://github.com/Vita3K/compatibility/assets/147109658/bbef3be5-480b-45b8-bb87-e1c5cd3da92a)
![Screenshot_20231007-083438](https://github.com/Vita3K/compatibility/assets/147109658/9c0afbdb-7e84-435a-ade2-e4b514cc1afb)
![Screenshot_20231007-083442](https://github.com/Vita3K/compatibility/assets/147109658/1a626a94-4d6f-4603-836e-ac7a3bf1ab6a)
![Screenshot_20231007-083847](https://github.com/Vita3K/compatibility/assets/147109658/c76be869-eeb4-4c26-a54e-b7398451ce1a)

# Log

# Recommended labels

- A Playable
- B Graphics bug

**Comment by nishinji** [comment]
sorry, this repo is not for android
