### ISSUE TITLE
Toukiden 2 [PCSH10022]

### ISSUE THREAD

**Issue by yuezhixuyu** [Vita3K/compatibility#2356]
Toukiden 2 Big blade cut The move will cause the device to crash，The device CPU is Qualcomm Snapdragon 870，Hope to repair and optimize as soon as possible. Thank you

https://github.com/Vita3K/compatibility/assets/147332603/c3f0eb92-1def-4439-b4e6-cb4f1f3cd889

https://github.com/Vita3K/compatibility/assets/147332603/50f61280-6632-45fb-9752-87a5b1d56c71

**Comment by Croden1999** [comment]
issue report not supported Android version, please submit here https://github.com/Vita3K/Vita3K-Android/issues.

问题报告不支持安卓版本，请在此处提交
