### ISSUE TITLE
Rayman® Origins [PCSB00079]

### ISSUE THREAD

**Issue by DextereggsYT** [Vita3K/compatibility#2357]
# App summary
- App name: Rayman® Origins
- App serial: PCSB00079
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: DextereggsYT 
- OS: Android, Kernel Version: 12
- CPU: Sapdragon 732
- GPU: Adreno
- RAM: 8 GB

# Issues
 glitched textures in levels where the water is abundant, the "sound issue" looks to be fixed, but still having bugs in certain areas

# Screenshots
![image](https://?)
![Screenshot_2023-10-08-20-11-57-651_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/147361053/d8a44e2e-8097-4e56-98bf-00e21b41807b)

# Log

# Recommended labels

- Ingame +
- graphic bug
- C?

**Comment by Croden1999** [comment]
issue report not for Android version, please submit here https://github.com/Vita3K/Vita3K-Android/issues.

**Comment by DextereggsYT** [comment]
> issue report not for Android version, please submit here https://github.com/Vita3K/Vita3K-Android/issues.

My apologies, I have to delete this post and upload it on the Android page?
