### ISSUE TITLE
ONE PIECE BURNING BLOOD [PCSB00893]

### ISSUE THREAD

**Issue by Ch4terMfag** [Vita3K/compatibility#2360]
# App summary
- App name: ONE PIECE BURNING BLOOD
- App serial: PCSB00893
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Poco F4 128/6
- OS: Android
- CPU: Snapdragon 870
- GPU: Adreno 650
- RAM: 6 GB

# Issues
- Dont have text
- It can crashes

**Comment by nishinji** [comment]
this repo is not for android
