### ISSUE TITLE
Sly Cooper: Viajantes do tempo [PCSA00068]

### ISSUE THREAD

**Issue by nandinhofly** [Vita3K/compatibility#2368]
# App summary
- App name: Sly Cooper: Viajantes do tempo
- App serial: PCSA00068
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Android 13
- CPU: Qualcomm Snapdragon 730 (SM7150)
- GPU: Adreno (TM) 618
- RAM: 6 GB LPDDR4X

# Issues

# Screenshots
![
![Screenshot_20231024_215522_Vita3K](https://github.com/Vita3K/compatibility/assets/62525535/a8aee222-c62f-41c3-b496-1b5beabf73e8)
](https://?)

# Log

# Recommended labels

- A Jogo inicia normal ate a tela de menu, quando clica em novo jogo, o sistema fecha subitamente.
- B?
- C?

**Comment by nishinji** [comment]
- Use English
- Add log
- This repo is not for Android
