### ISSUE TITLE
Mortal Kombat [PCSE00023]

### ISSUE THREAD

**Issue by MobileusPC** [Vita3K/compatibility#2371]
# App summary
- App name: Mortal Kombat
- App serial: PCSE00023
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: MibileusPC
- OS: Android
- CPU: Qualcomm Snapdragon 720g
- GPU: Adreno
- RAM: 6 GB

# Issues

This game was previously marked green, which indicates playable.  suddenly turned gray with unknown status
# Screenshots
![image](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by KaneDbD** [comment]
invalid
