### ISSUE TITLE
STREET FIGHTER X TEKKEN [PCSG00063]

### ISSUE THREAD

**Issue by tipsyGnostalgik** [Vita3K/compatibility#2382]
# App summary
- App name: ?
- App serial: ?
- App version: ?

# Vita3K summary
- Version: v?
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

# Test environment summary
- Tested by: ?
- OS: Windows 10/macOS/Linux Distro, Kernel Version? 
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues

# Screenshots
![](https://?)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by tipsyGnostalgik** [comment]
OH MY GOD I PUBLISHED EARLY BY ACCIDENT HOW DO I DELETE PLEASE HELP

**Comment by tipsyGnostalgik** [comment]
DAMN IT I DIDN'T KNOW THAT I CAN'T SUBMKT REPORTS FROM ANDROID I'M SORRY D:

**Comment by nishinji** [comment]
ok👍
