### ISSUE TITLE
Yomawari: Night Alone [PCSE00909]

### ISSUE THREAD

**Issue by German-Herrador** [Vita3K/compatibility#2386]
# App summary
- App name: Yomawari: Night Alone
- App serial: PCSE00909
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3423
- Commit hash: https://github.com/vita3k/vita3k/commit/23d02897
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: ? 
- OS: Android 12
- CPU: Snapdragon 732G
- GPU: Adreno 618
- RAM: 4 GB

# Issues
No issues

# Screenshots

https://github.com/Vita3K/compatibility/assets/109971356/56e92487-1d7e-4fd3-b982-48383540bc47

# Log

# Recommended labels
Playable
- A?
- B?
- C?

**Comment by nishinji** [comment]
this repo is not for android
