### ISSUE TITLE
LittleBigPlanet PS Vita (PCSA00017) macOS iMac/MacBooks Only

### ISSUE THREAD

**Issue by tronbrahim1beacon** [Vita3K/compatibility#2392]
LittleBigPlanet PS Vita (PCSA00017) macOS iMac/MacBooks Only
PCSA00017
Ingame+

# App summary
LittleBigPlanet PlayStation Vita
- App serial PCSA00017
- App version: 1.22

**Comment by nishinji** [comment]
lack of info

**Comment by rafciu41** [comment]
is PCSA00017 us or eu version
