### ISSUE TITLE
SENRAN KAGURA Bon Appetit! (Hanzo x Crimson Squad) [PCSE00471]

### ISSUE THREAD

**Issue by Yukiis96** [Vita3K/compatibility#2394]
# App summary
- App name: SENRAN KAGURA Bon Appetit! (Hanzo x Crimson Squad)
- App serial: PCSE00471
- App version: 1.00

# Vita3K summary
- Version: v0.1.9
- Build number: 3533
- Commit hash: https://github.com/vita3k/vita3k/commit/21004473
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: IMANHOL,OR
- OS: Android 11, redmi 9
- CPU: Mediatek Helio G80
- GPU: Mali G52 MC2
- RAM: 4 GB

# Issues

No hay problemas ni fallas gráficas

# Screenshots

https://github.com/Vita3K/compatibility/assets/96699015/669d82e1-f3b7-49f0-b967-c6af38acb2fa

# Log

# Recommended labels
-https://github.com/Vita3K/compatibility/labels/Playable

**Comment by Yukiis96** [comment]
### **__**

**Comment by nishinji** [comment]
this repo is not for android
