### ISSUE TITLE
DJMAX TECHNIKA TUNE [PCSG00070]

### ISSUE THREAD

**Issue by aguylberjun** [Vita3K/compatibility#2418]
# App summary
- App name: DJMAX TECHNIKA TUNE 
- App serial: PCSG00070
- App version: 1.0

# Vita3K summary
- Version: v0.1.9
- Build number: 3561

- CPU backend: Dynarmic 
- GPU backend: Vulkan 

# Test environment summary
- Tested by: Aguylber Junior 
- OS: Android 13 , M23 5G
                                                                                         
                                                                                        
- CPU: Snapdragon 750G Qualcomm SM7225
- GPU: Adreno 619
- RAM: 6 GB

# Issues
When i start playing the game random Glitches all the sudden and save data bug 

# Screenshots
![Screenshot_20240116_173856_Vita3K](https://github.com/Vita3K/compatibility/assets/154929947/64c74c18-2308-4ae8-8771-87b5f15036b9)
![Screenshot_20240116_174054_Vita3K](https://github.com/Vita3K/compatibility/assets/154929947/2a50abc3-878c-458c-b7bf-afe975fd16a3)

# Recommended labels

- "graphics bug"
- "Savedata Bug"
- "Playable"

**Comment by nishinji** [comment]
this repo is not for android
