### ISSUE TITLE
Diabolik Lovers Limited V Edition [PCSG00272]

### ISSUE THREAD

**Issue by ayatosamaex** [Vita3K/compatibility#2478]
### App summary

- App name: Diabolik Lovers Limited V Edition 
- App serial: [PCSG00272]
- App version: v1.01

### Vita3K summary

- Version: v.0.2.0
- Build number: 3588-2424f92c
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: 
- GPU backend: 

### Test environment summary

- Tested by: Ayatosamaex
- OS: Windows 11
- CPU AMD Ryzen 5 2600
- GPU: Readeon RX470
- RAM: 16

### Issues

I have problem with background, specyfically his lack

### Log

[vita3k.txt](https://github.com/Vita3K/compatibility/files/14733237/vita3k.txt)

### Recommended labels

![image](https://github.com/Vita3K/compatibility/assets/164669593/a6f7674b-f830-41d2-a5bd-6476078953e6)

**Comment by Megami-Parhill** [comment]
I had the same issue, solved it by doing these configurations.
![imagem_2024-05-07_193027913](https://github.com/Vita3K/compatibility/assets/169210096/481579c2-cdf4-438c-a637-38e193914f99)
