### ISSUE TITLE
ONE PIECE Unlimited World Red [PCSE00423]

### ISSUE THREAD

**Issue by azalalqas** [Vita3K/compatibility#2492]
# App summary
- App name: ONE PIECE Unlimited World Red
- App serial: PCSE00423
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3584
- Commit hash: https://github.com/vita3k/vita3k/commit/25d9b25e
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: me
- OS: Android 14/one ui 6.0 
- CPU: Qualcomm Snapdragon 888 5G (SM8350)
- GPU: don't know
- RAM: 6 GB

# Issues: characters don't load in properly text gets slightly cut

# Screenshots
![image](https://?)

# Log

# Recommended labels: ingame

**Comment by azalalqas** [comment]
Characters don't load in properly and text gets partially cut.

**Comment by azalalqas** [comment]
I've only for 15ish minutes so I'm not entirely sure also I'm playing at 2x setting because my phone has a 1080p display

**Comment by nishinji** [comment]
Thank you for finding the bug in the bot. I was not sure of the cause :/
When opening a github issue, please refer to others' reports and follow the template.
