### ISSUE TITLE
新星抜擢 ドライブガールズ [PCSG00934]

### ISSUE THREAD

**Issue by yamada0773** [Vita3K/compatibility#2498]
# App summary
- App name: 新星抜擢 ドライブガールズ
- App serial: PCSG00934
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3594
- Commit hash: https://github.com/vita3k/vita3k/commit/d49480f8
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: hello 
- OS: Microsoft Windows 11  (build 22631)
- CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
- GPU: NVIDIA GeForce RTX 3060
- RAM: 16 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

- Playable
- B?
- C?

**Comment by nishinji** [comment]
If logs and screenshots are not provided by tomorrow, will be closed

**Comment by nishinji** [comment]
lack of info
