### ISSUE TITLE
PUNCHLINE [PCSE01288]

### ISSUE THREAD

**Issue by SummerAStrand** [Vita3K/compatibility#2502]
# App summary
- App name: PUNCHLINE
- App serial: PCSE01288
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3584
- Commit hash: https://github.com/vita3k/vita3k/commit/25d9b25e
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: SummerAStrand
- OS: Android 13
- CPU: Unisoc T820 processor, 6nm EUV 5G SOC chip Octa-core 1*A76@2.7GHz+3*A76@2.3GHz+4*A55@2.1GHz
- GPU: Quad Core Mali- G57 850MHz
- RAM: 8GB LPDDR4X

# Issues
Game crashes in less than a minute after starting a new game (title screen is fine)

# Screenshots
![image](https://?)

# Log

# Recommended labels
- Bootable
- crash

**Comment by nishinji** [comment]
lack of info and andriod report
