### ISSUE TITLE
Pinball Heroes - Complete (PCSA00109) (NTSC)

### ISSUE THREAD

**Issue by Smash1977** [Vita3K/compatibility#2509]
Black screen right after launching the game. Audio keeps working.

**Comment by Smash1977** [comment]
With all due respect, I don't have a clue as to what to write in the template. And honestly, I've got no time to lose trying to understand all those complicated info I need to provide. You perfectly know what game I am talking about and I'm just a gamer who wanted to help, not a tech. So, sorry I am not going to edit anything and you are free to delete my account, if you like.

**Comment by nishinji** [comment]
"I am stupid enough not to have to find out how the repository is managed, nor do I have to read the README."

**Comment by Smash1977** [comment]
A genius has come to teach me how to live a virtuous life... 🙄 Please, fly down.

And no, simply I don't have the time to read or - if you prefer it this way - I am too lazy to do that, my Life Sensei.
I'll leave it all to you, you probably live on Github rent-free, but that's not for me.
End of communications.
