### ISSUE TITLE
Diabolik Lovers Limited [PCSG00272]

### ISSUE THREAD

**Issue by sherry5122** [Vita3K/compatibility#2517]
# App summary
- App name: Diabolik Lovers Limited V Edition
- App serial:  [PCSG00272]
- App version: v1.01

# Vita3K summary
- Version: Unsure how to check but latest version from Vita3k website directly, downloaded few days ago
- Build number: 3596
- Commit hash: https://github.com/vita3k/vita3k/commit/418f234 
- CPU backend: Dynarmic 
- GPU backend: OpenGL

# Test environment summary
- Tested by: sherry5122
- OS: Windows 11
- CPU: AMD Ryzen 7 5700U with Radeon Graphics            1.80 GHz
- GPU: AMD Radeon(TM) Graphics
- RAM: 16.0 GB (15.3 GB usable)

# Issues
Game is playable, audio, speech and characters work fine but the background is a black screen from the start of gameplay. 

# Screenshots
![Screenshot (215)](https://github.com/Vita3K/compatibility/assets/169489622/2746847d-ed15-4761-91ae-b7f3af6dcc1b)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/15282363/vita3k.log)

# Recommended labels
Playable, black screen

First time using this website and Vita3k so there's a lot of information I don't understand. If you're able to help me, I will provide the information to the best of my abilities :) I don't know what commit hash is, so i used a random one. Thank you!

**Comment by nishinji** [comment]
https://github.com/Vita3K/compatibility/issues/452
