### ISSUE TITLE
Diabolik Lovers Limited V Edition [PCSG00272]

### ISSUE THREAD

**Issue by sherry5122** [Vita3K/compatibility#2518]
# App summary
- App name: Diabolik Lovers Limited V Edition 
- App serial: PCSG00272
- App version: v1.01

# Vita3K summary
- Version: Unsure but download few days ago
- Build number: 3596 (not sure what this is)
- Commit hash: https://github.com/vita3k/vita3k/commit/418f234
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: me
- OS: Windows 11 
                                                                    
- CPU: AMD Ryzen 7 5700U
- GPU: AMD Radeon (TM) Graphics 
- RAM: 16 GB

# Issues
On Ayato Dark route for Chapter 7, I can generate all the text but then it gets stuck on that screen. Keyboard doesn't work but the audio is still there.

# Screenshots
![IMG_20240511_181043_594](https://github.com/Vita3K/compatibility/assets/169489622/44b80015-3ce2-47c4-9dde-e4dd18805a3c)

# Log
Will upload soon.

# Recommended labels
Playable 

Don't know which label to put but this game is labeled playable on vita3k compatibility list on their website.

**Comment by uglyvampire246** [comment]
hey did u find a solution to this problem?

**Comment by sherry5122** [comment]
> hey did u find a solution to this problem?

hi there, stopped playing this game already but i was just being dumb 😭. just click any of the blue words to proceed, however this does affect the route. u can google to learn more. hope this helps!

**Comment by uglyvampire246** [comment]
i wasnt expecting u to answer but THANK YOU SOO MUCH OMG it finally worked  😭🙏ive been stuck for 3 days and thought smt was wrong w the game lol
