### ISSUE TITLE
Dungeon Hunter: Alliance [PCSB00041]

### ISSUE THREAD

**Issue by Tahm369** [Vita3K/compatibility#2523]
# App summary
- App name: Dungeon Hunter: Alliance
- App serial: PCSB00041
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3596
- Commit hash: https://github.com/vita3k/vita3k/commit/418f2343
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: deck 
- OS: SteamOS Holo
- CPU: AMD Custom APU 0932
- GPU: AMD Radeon Graphics (RADV VANGOGH)
- RAM: 14 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

playable

**Comment by jaloji** [comment]
With Vita3K v0.2.0 3654-10b8bf32, Playable with Vulkan.
![Capture d’écran 2024-10-01 203056](https://github.com/user-attachments/assets/8a5f027b-0770-4eae-8490-cdc123dce83e)
