### ISSUE TITLE
槍彈辯駁 [PCSH00055]

### ISSUE THREAD

**Issue by Tahm369** [Vita3K/compatibility#2533]
# App summary
- App name: 槍彈辯駁
- App serial: PCSH00055
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3598
- Commit hash: https://github.com/vita3k/vita3k/commit/d4c0c499
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: 22095 
- OS: Microsoft Windows 11 Professional (build 22631)
- CPU: 13th Gen Intel(R) Core(TM) i9-13900KF
- GPU: NVIDIA GeForce RTX 4090
- RAM: 65 GB

# Issues

# Screenshots
![image](https://?)

# Log

# Recommended labels

playable

**Comment by nishinji** [comment]
lack of info (Screenshots and log)
