### ISSUE TITLE
Amagami [PCSG00291]

### ISSUE THREAD

**Issue by JhonnySalles** [Vita3K/compatibility#300]
[vita3k.log](https://github.com/Vita3K/compatibility/files/3963207/vita3k.log)

# Game summary
- Game name: Anagami
- Game serial: PCSG00291
- Game version: 1.0

# Vita3K summary
- Version: v3.411
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 

# Test environment summary
- Tested by: JhonnySalles
- OS: Windows 10
- CPU: Intel i5-2400
- GPU: NVIDIA GTX 960
- RAM: 16 GB

# Issues

Unicorn error 0x6 at: start PC: 0x810C91D7 error PC 0x8100DECC LR: 0x810057F7

# Screenshots
![image](https://user-images.githubusercontent.com/43912638/70840280-fbf8d780-1def-11ea-85da-ee248cd7d4e6.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/3963212/vita3k.log)

# Recommended labels

- Nothing
- unicorn error

**Comment by IllusionMan1212** [comment]
You're using a Vitamin dump, please dump the game using maidump and retest.
Vitamin dumps are currently unsupported

**Comment by JhonnySalles** [comment]
I searched for some tutorial on installing MaiDumpTool, I didn't find anything that could help.
I did the default installation, like a game, but trying to access it presents the same error.
I get a similar error with FAGDec.vpk

![image](https://user-images.githubusercontent.com/43912638/70855422-5bff8480-1ea9-11ea-8125-efa454ba06cd.png)

![image](https://user-images.githubusercontent.com/43912638/70855426-66ba1980-1ea9-11ea-9e4a-1a9a95048b77.png)

[vita3k.log](https://github.com/Vita3K/compatibility/files/3964412/vita3k.log)

**Comment by IllusionMan1212** [comment]
@JhonnySalles you need to install maidumptool on your **vita** and then dump the game from there
