### ISSUE TITLE
Persona 4 Golden [PCSB00245] 

### ISSUE THREAD

**Issue by Ezequiel0914** [Vita3K/compatibility#332]
# Game summary
Game name: Persona 4 Golden
Game serial: PCSB00245
Game version: 01.00

# Vita3K summary
- Version: v0.1
- Build number: 1316-b927afa0
- Commit hash: https://github.com/Vita3K/Vita3K/commit/b927afa0

# Test environment summary
- Tested by: Ezequiel0914
- OS: Windows 10 Pro 18.363.535
- CPU: AMD FX-6300
- GPU: AMD R7 260X
- RAM: 16 GB

# Issues
After you enter Yukiko's Castle, the game crashes.

# Screenshots
https://i.imgur.com/LCr1iZv.png

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/4049737/vita3k.log)

# Recommended labels

- Ingame -
- Crash

**Comment by IllusionMan1212** [comment]
Duplicate issue.
Please check if the has been reported prior to opening a new issue.
