### ISSUE TITLE
TuneIn [PCSB00407]

### ISSUE THREAD

**Issue by HorrorTroll** [Vita3K/compatibility#34]
# Game summary
- Game name: TuneIn
- Game serial: PCSB00407

# Vita3K summary
- Version: v0.1
- Build number: 242-01946ef
- Commit hash: https://github.com/vita3k/vita3k/commit/01946ef 

# Test environment summary
- Tested by: HorrorTroll
- OS: Windows 8.1
- CPU: Intel Core i5-4200H
- GPU: Nvidia Geforce GTX 950M
- RAM: 6 GB DDR3

# Issues

Crash

# Screenshots
Not for moment

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/1973987/vita3k.log)

# Recommended labels

Crash

**Comment by scribam** [comment]
# Vita3K summary
- Version: v0.1
- Build number: 1737
- Commit hash: https://github.com/vita3k/vita3k/commit/ec3eaab4

# Screenshots
![Capture](https://user-images.githubusercontent.com/25406440/98796608-ddd69580-240b-11eb-9b4a-dd6b33e9d599.PNG)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/5523244/vita3k.log)

**Comment by othmanead** [comment]
# Vita3K summary
- Version: v0.1.5
- Build number: 2630
- Commit hash: https://github.com/vita3k/vita3k/commit/18dacae2
- CPU backend: Dynamic  

# Test environment summary
- Tested by: othmanead
- OS: Windows 11
- CPU: Intel i5-10300H
- GPU: RTX 3060 mobile
- RAM: 16 GB


# Issue: 
- Game goes to intro but needs an internet connection 

# Screenshots:
![image](https://user-images.githubusercontent.com/106798110/172073084-e3a9460c-4e81-4f0e-9ce0-3f5440c2b9c4.png)
![image](https://user-images.githubusercontent.com/106798110/172073188-cd827005-89ac-449c-92cb-0e630b05c892.png)




# Log

[vita3k.log](https://github.com/Vita3K/compatibility/files/8840891/vita3k.log)




# Recommended labels

- Intro

**Comment by github-user1112** [comment]
Should the Intro label be removed from this as its been closed and replaced with different post?
