### ISSUE TITLE
Fruit Ninja [PCSB00273]

### ISSUE THREAD

**Issue by FranciscoCarlosJR** [Vita3K/compatibility#345]
# Game summary
- Game name: Fruit Ninja
- Game serial: PCSB00273
- Game version: 1.00

# Vita3K summary
- Version: 0.1
- Build number: 1364
- Commit hash: https://github.com/vita3k/vita3k/commit/

# Test environment summary
- Tested by: FranciscoCarlosJunior
- OS: Windows 10
- CPU: Intel Core i5 6200U
- GPU: NVIDIA Geforce GTX 920MX
- RAM: 8 GB

# Issues
4 Uniplemented Services
A Bunch of Missing NIDS
2 Sce Kernel Error

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/4127715/vita3k.log)

# Recommended labels
Nothing/NID Missing

**Comment by Zangetsu38** [comment]
wrong report, vitamin dump not  compatbile
