### ISSUE TITLE
Mahouka Koukou no Rettousei: Out of Order [PCSG00456]

### ISSUE THREAD

**Issue by wcy1216** [Vita3K/compatibility#348]
# Game summary
- Game name: 魔法科高校の劣等生Out Of Order
- Game serial: PCSG00456
- Game version: 01.00

# Vita3K summary
- Version: v0.1
- Build number: 1365
- Commit hash: https://github.com/vita3k/vita3k/commit/0e17fd18305200790861e8f24be35107f0eed5de

# Test environment summary
- Tested by: wcy1216
- OS: Windows 10
- CPU: Intel i7-9750H
- GPU: NVIDIA GeForce RTX 2060
- RAM: 16 GB

# Issues
It is possible to load in menu but exit when I start the game  

# Screenshots
![](https://?)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/4137880/vita3k.log)

# Recommended labels

- A?
- B?
- C?

**Comment by benderscruffy** [comment]
Vita3K v0.1.5 2734-0751c4ee
goes ingame
text missing from the menus
crashes at the beginning of the game
[vita3k.log](https://github.com/Vita3K/compatibility/files/9078325/vita3k.log)
![Vita3K v0 1 5 2734-0751c4ee _ 魔法科高校の劣等生 Out of Order (PCSG00456) _ OpenGL _ 39 ms_frame (26 frames_sec) _ 960x544  10_07_2022 10_42_27 AM](https://user-images.githubusercontent.com/2696404/178129227-e81d3cb6-a99e-4ff2-8afd-373c6cd4af07.png)
![Vita3K v0 1 5 2734-0751c4ee _ 魔法科高校の劣等生 Out of Order (PCSG00456) _ OpenGL _ 67 ms_frame (15 frames_sec) _ 960x544  10_07_2022 10_46_38 AM](https://user-images.githubusercontent.com/2696404/178129228-75e537b7-882c-46a1-96da-c897bbd87005.png)
![Vita3K exe 10_07_2022 10_43_22 AM](https://user-images.githubusercontent.com/2696404/178129230-cb05e22f-b49c-4b86-8564-41eb1633ffd4.png)
