### ISSUE TITLE
Resistance Burning Skies

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/compatibility#4]
# Game summary
- Game name: Resistance Burning Skies
- Game serial: PCSA00008

# Vita3K summary
- Version: v0.1
- Build number: 240-f804620
- Commit hash: https://github.com/vita3k/vita3k/commit/3137d1f

# Test environment summary
- Tested by: Zangetsu38
- OS: Windows 10 17.134.5
- CPU: AMD Ryzen 7 2700X
- GPU: Nvidia MSI GTX 1080 Ti Trio 
- RAM: 16 GB DDR4

# Issues
Crash after start boot with rose screen

# Screenshots
Not for moment

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/1968888/vita3k.log)

# Recommended labels
Crash

**Comment by Rinnegatamante** [comment]
Seems like the game had been dumped with Vitamin. You should stick with mai dumps.

**Comment by Zangetsu38** [comment]
log updated, and final commit have again improved boot

**Comment by Rinnegatamante** [comment]
The log still refers to a Vitamin dump.

**Comment by Zangetsu38** [comment]
WTF what i have used before xD 💀
