### ISSUE TITLE
Treasure Park [PCSA00060]

### ISSUE THREAD

**Issue by meowthed** [Vita3K/compatibility#443]
# App summary
- App name: Treasure Park
- App serial:  PCSA00060
- App version: 1.00

# Vita3K summary
- Version: v0.1
- Build number: 1822
- Commit hash: https://github.com/Vita3K/Vita3K/commit/4938ca8b164147e462e01af7eec4ec3e0a475101 

# Test environment summary
- Tested by: Arnold Secret
- OS: Windows 10
- CPU: Intel Core i7-4500U
- GPU: NVIDIA Geforce GT 740M
- RAM: 8 GB

# Issues
Unicorn error, only gets to epilepsy warning before crash.

# Screenshots
![Untitled](https://user-images.githubusercontent.com/41223243/104276811-95f1ee80-54e0-11eb-8496-fd7685d95a2e.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/5800095/vita3k.log)

**Comment by Zangetsu38** [comment]
this games globality works, you need install firmware for can loading one module request 
![image](https://user-images.githubusercontent.com/5261759/104277504-3c210280-54a7-11eb-91af-2538e183038e.png)

**Comment by arnoldsecret** [comment]
Clone of https://github.com/Vita3K/compatibility/issues/141, one needs to close.
