### ISSUE TITLE
この素晴らしい世界に祝福を！～希望の迷宮と集いし冒険者たち～ [PCSG01258]

### ISSUE THREAD

**Issue by meowthed** [Vita3K/compatibility#457]
# App summary
- App name: この素晴らしい世界に祝福を！～希望の迷宮と集いし冒険者たち～
- App serial: PCSG01258
- App version: 1.01

# Vita3K summary
- Version: v0.1
- Build number: 1827
- Commit hash: https://github.com/Vita3K/Vita3K/commit/0f2aabb900ddd27078df540bfe8f1d177ff0445d 

# Test environment summary
- Tested by: Arnold Secret
- OS: Windows 10
- CPU: Intel Core i7-4500U
- GPU: NVIDIA Geforce GT 740M
- RAM: 8 GB

# Issues
Reaches to menu, then stuck on black screen when selecting new game.

# Screenshots
![Untitled](https://user-images.githubusercontent.com/41223243/104798428-a74d3a80-5801-11eb-874b-0b641e98d28d.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/5823915/vita3k.log)

**Comment by arnoldsecret** [comment]
Clone of https://github.com/Vita3K/compatibility/issues/341, closing.
