### ISSUE TITLE
Photo Kano Kiss (フォトカノ Kiss) [PCSG00139]

### ISSUE THREAD

**Issue by xqianz** [Vita3K/compatibility#469]
# App summary
- App name: フォトカノ Kiss
- App serial: PCSG00139
- App version: 1.04

# Vita3K summary
- Version: v0.1.2
- Build number: 571652
- Commit hash: https://github.com/vita3k/vita3k/commit/2aaa9e3 

# Test environment summary
- Tested by: xqianz
- OS: Windows 10
- CPU: Intel Core i5 9300H
- GPU: NVIDIA GeForce GTX 1050
- RAM: 12GB

# Issues
This game seems installed succesfully but it did not show up in the game list of Vita3k

# Screenshots
![](https://?)

# Log
[Vita3k.txt](https://github.com/Vita3K/compatibility/files/6034088/Vita3k.txt)

# Recommended labels

- Nothing

**Comment by hobyst** [comment]
The game dump used to report this game is a Mai dump, which is unsupported by the emulator.

**Comment by Zangetsu38** [comment]
@hobyst hmhm, maidump is compatible with emu, you confunded with vitamin :D

**Comment by Zangetsu38** [comment]
issue already exist, and you have installed only patch and no game, normal no  appear in game list, game is not insalled

**Comment by xqianz** [comment]
Okay, I understand. Thanks for your reply and investigation, I appreciate it very much
