### ISSUE TITLE
Collar x Malice - USA - Game ID: PCSE01011

### ISSUE THREAD

**Issue by luluchan93** [Vita3K/compatibility#505]
# App summary
- App name: Collar x Malice 
- App serial: PCSE01011
- App version: USA

# Vita3K summary
- Version: v 0.1.2
- Build number: ?
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend:              

                          

# Test environment summary
- Tested by: me
- OS: Windows 8.1
- CPU: Intel i3-3110M 
- GPU: Intel 2.40 GHz
- RAM: 4 Gb

# Issues

# Screenshots
![](https:// 
![image](https://user-images.githubusercontent.com/85079597/120119082-a5bb5800-c18d-11eb-86ab-52e80f4a1bc8.png)

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
Ouille this screen and tour computer 🥶💀

**Comment by Zangetsu38** [comment]
And i close this game is already set here’ all time search id of game before open New issue
