### ISSUE TITLE
New Game! -The Challenge Stage!- [PCSG00903]

### ISSUE THREAD

**Issue by Hazuki-san** [Vita3K/compatibility#517]
# App summary
- App name: NEW GAME! -THE CHALLENGE STAGE!-
- App serial: PCSG00903
- App version: 1.00

# Vita3K summary
- Version: v0.1.3
- Build number: 2265
- Commit hash: https://github.com/vita3k/vita3k/commit/bf29a917b3d8fcc7bd81cfa0405fa80a3a3ae4fd
- CPU backend: Dynarmic

# Test environment summary
- Tested by: Hazuki-san
- OS: Windows 10 20H2 (19042.928) [Microsoft Windows NT 6.3.9600.0]
- CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz 2.30 GHz
- GPU: GeForce 610M/PCIe/SSE2
- RAM: 5 GB (4GBx1, 1GBx1)

# Issues
- The game seems to load fine but after the OP.mp4 the game froze and the whole OS freezes with audio glitches (BEEEEEEEEEP)

# Screenshots
![image](https://user-images.githubusercontent.com/27200811/130855449-2ca8968c-3554-489c-991d-8772f7f3a784.png)
![image](https://user-images.githubusercontent.com/27200811/130855577-41f6f729-936c-4db6-b455-bfb756c16f74.png)
![image](https://user-images.githubusercontent.com/27200811/130855594-9e4a0b25-ab94-4a9c-8954-90042a613fcd.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/7049576/vita3k.log)

# Recommended labels
- Intro
- crash
- kernel issue

**Comment by Zangetsu38** [comment]
Double compat check first #107
