### ISSUE TITLE
Tokyo Ghoul: Jail [PCSG00615]

### ISSUE THREAD

**Issue by FruitPunchSamuraiG0700** [Vita3K/compatibility#528]
# App summary
- App name: Tokyo Ghoul: Jail (東京喰種トーキョーグール JAIL)
- App serial: PCSG00615
- App version: 1.00

# Vita3K summary
- Version: 0.1.3
- Build number: 2269
- Commit hash: https://github.com/vita3k/vita3k/commit/9cb2063d50ae5fe0603594ea6122069cf8d67510 
- CPU backend: Dynarmic           

                          

# Test environment summary
- Tested by: WhiteRonin
- OS: Windows 10
- CPU: Intel i5 11th Gen @2.4GHz
- GPU: Intel Iris Xe integrated graphics
- RAM: 8 GB

# Issues

Minor drop in audio quality while ingame.

Note*: The game is playable, but I haven't completed it so I would like to say the game is ingame+. It's a visual novel.

# Screenshots
![tg1](https://user-images.githubusercontent.com/71183624/135122020-1caa3f00-7c79-4fb8-b43d-8cb3a2583b77.png)

![tg2](https://user-images.githubusercontent.com/71183624/135122155-9e81a324-4110-48d6-bc75-67f4c43748f2.png)

![Screenshot_2](https://user-images.githubusercontent.com/71183624/135127205-581edcaf-7381-4a43-8461-d7ef35a49d0b.png)

![Screenshot_3](https://user-images.githubusercontent.com/71183624/135127328-bc6e65e9-0efc-4444-84e3-7018a84af800.png)

# Log

[vita3k.log](https://github.com/Vita3K/compatibility/files/7245934/vita3k.log)

# Recommended labels

- Ingame+ or playable

**Comment by Zangetsu38** [comment]
@FruitPunchSamuraiG0700 sorryy, you have create double issue, update with last build in other already exist
