### ISSUE TITLE
PCSF00001 [Uncharted: золотая бездна™] Menu!

### ISSUE THREAD

**Issue by deatrocker** [Vita3K/compatibility#612]
# App summary
- App name: Uncharted: золотая бездна™
- App serial: PCSF00001
- App version: 1.0

# Vita3K summary
- Version: v0.1.5
- Build number: 2570-ffa66d88
- Commit hash: https://github.com/Vita3K/Vita3K/commit/ffa66d88de3a1b25bed47b5b85074b3b99778ee6
- CPU backend: Dynarmic

# Test environment summary
- Tested by: 7GEN emulation news (https://vk.com/rpcs3)
- OS: Windows 10
- CPU: Intel
- GPU: NVIDIA 1060 6G
- RAM: 16 GB

# Issues
No crash now, passed to menu, after - freeze

# Screenshots
Video:
https://vk.com/video-75040291_456267155
Screenshot:
![Desktop Screenshot 2022 05 21 - 18 42 42 20](https://user-images.githubusercontent.com/20367262/169659023-370f41ec-c03d-4857-bd55-9a5d81c9abea.png)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
issue already exist
