### ISSUE TITLE
PCSF00021 [LittleBigPlanet™ PlayStation®Vita]

### ISSUE THREAD

**Issue by deatrocker** [Vita3K/compatibility#613]
# App summary
- App name: LittleBigPlanet™ PlayStation®Vita
- App serial: PCSF00021
- App version: 1.0

# Vita3K summary
- Version: v0.1.5
- Build number: 2570-ffa66d88
- Commit hash: https://github.com/Vita3K/Vita3K/commit/ffa66d88de3a1b25bed47b5b85074b3b99778ee6
- CPU backend:  Dynarmic

# Test environment summary
- Tested by: 7GEN emulation news (https://vk.com/rpcs3)
- OS: Windows 10
- CPU: Intel i7 7700k
- GPU: NVIDIA 1060 6G
- RAM: 16 GB

# Issues
Ingame with broken graphics

# Screenshots
Video:
https://vk.com/video-75040291_456267156
Screenshot:
![Desktop Screenshot 2022 05 21 - 19 05 18 97](https://user-images.githubusercontent.com/20367262/169659967-7b801228-0acf-459b-ac21-4cfe468bac11.png)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
no write state of game inside title, and before create new issue, check if id of game already exist, here is doublon
