### ISSUE TITLE
PCSE00015 [Shinobido 2: Revenge of Zen] Ingame playable!

### ISSUE THREAD

**Issue by deatrocker** [Vita3K/compatibility#614]
# App summary
- App name: Shinobido 2: Revenge of Zen
- App serial: PCSE00015
- App version: 1.0

# Vita3K summary
- Version: v0.1.5
- Build number: 2570-ffa66d88
- Commit hash: https://github.com/Vita3K/Vita3K/commit/ffa66d88de3a1b25bed47b5b85074b3b99778ee6
- CPU backend:  Dynarmic

# Test environment summary
- Tested by: 7GEN emulation news (https://vk.com/rpcs3)
- OS: Windows 10
- CPU: Intel i7 7700k
- GPU: NVIDIA 1060 6G
- RAM: 16 GB

# Issues
Ingame with Gameplay

# Screenshots
Video:
https://vk.com/video-75040291_456267157
Screenshot:
![Vita Screenshot 2022 05 21 - 20 24 10 74](https://user-images.githubusercontent.com/20367262/169662743-f1f2d187-81df-4f6b-9a5b-0c9bfd3fd053.png)

# Log

# Recommended labels

- A?
- B?
- C?

**Comment by Zangetsu38** [comment]
same before, already exist, using post exist and post your screenshot and log on it
