### ISSUE TITLE
Thomas Was Alone [PCSE00258]

### ISSUE THREAD

**Issue by HorrorTroll** [Vita3K/compatibility#68]
# Game summary
- Game name: Thomas Was Alone
- Game serial: PCSE00258

# Vita3K summary
- Version: v0.1
- Build number: 311-e4d7a67
- Commit hash: https://github.com/vita3k/vita3k/commit/e4d7a67 

# Test environment summary
- Tested by: HorrorTroll
- OS: Windows 8.1
- CPU: Intel Core i5-4200H
- GPU: Nvidia Geforce GTX 950M
- RAM: 6 GB DDR3

# Issues

Crash

# Screenshots
Not for moment

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/1990056/vita3k.log)
[Patch vita3k.log](https://github.com/Vita3K/compatibility/files/1990057/vita3k.log)

# Recommended labels

Crash

**Comment by Zangetsu38** [comment]
Double listed
