### ISSUE TITLE
Digimon World: Next Order (CHI) [PCSH00261]

### ISSUE THREAD

**Issue by gymzatan** [Vita3K/compatibility#741]
# App summary
- App name: Digimon World: Next Order (CHI)
- App serial: PCSH00261
- App version: 1.03

# Vita3K summary
- Version: v0.1.5
- Build number: 2668
- Commit hash: https://github.com/vita3k/vita3k/commit/01948553 
- CPU backend: Dynarmic             

# Test environment summary
- Tested by: gymzatan
- OS: Windows 11
- CPU: AMD Ryzen 7 5800H
- GPU: AMD Radeon(TM) Graphics
- RAM: 16 GB

# Issues
Game runs with full speed. Runs beyond the menu but cannot get past the naming screen after choosing the protagonist. The game currently rejects all names including the default name (in Traditional Chinese), asking for English letter-only names. But names made of pure letters are also rejected.
Edit: Only long English names (>~10 letters) are accepted.

Walking animation is abnormal. 
Game occasionally crashes, especially when switching scenes, exiting the menu or viewing the Digidex.
The Digidex displays neither the images nor any text. 
Presumably one can get far ingame once past the naming screen.

# Screenshots
<img width="722" alt="Snipaste_2022-06-14_02-14-04" src="https://user-images.githubusercontent.com/79769470/173511027-2cedb484-1779-47d1-a3a3-2bf4474034fb.png">
<img width="722" alt="Snipaste_2022-06-14_02-23-39" src="https://user-images.githubusercontent.com/79769470/173511035-9f8c6e08-8d8c-455f-8835-aa7681dbd9c6.png">
<img width="722" alt="Snipaste_2022-06-14_03-11-07" src="https://user-images.githubusercontent.com/79769470/173515800-822eb41a-529a-4cce-a1b0-987cf28119fa.png">
<img width="722" alt="Snipaste_2022-06-14_07-35-32" src="https://user-images.githubusercontent.com/79769470/173568220-fa6c4b5d-6196-4fef-a812-c5a1e3a7ddc7.png">

![DGWK](https://user-images.githubusercontent.com/79769470/173526391-d9a98dc6-222e-4aab-883e-11225b023bf5.gif)
<img width="722" alt="Snipaste_2022-06-14_04-06-52" src="https://user-images.githubusercontent.com/79769470/173527642-a2eae14f-1860-46e5-964d-a88b0eed6624.png">
<img width="722" alt="Snipaste_2022-06-14_04-14-05" src="https://user-images.githubusercontent.com/79769470/173528394-5c7f03f1-4c82-49d8-8c92-defac3a84387.png">
<img width="722" alt="Snipaste_2022-06-14_04-01-18" src="https://user-images.githubusercontent.com/79769470/173528463-07e1d208-9e1e-4909-90d5-66947b8ec6f5.png">
<img width="722" alt="Snipaste_2022-06-14_04-02-01" src="https://user-images.githubusercontent.com/79769470/173528453-a561fc7b-bc59-437f-b257-4f865657e356.png">
<img width="722" alt="Snipaste_2022-06-14_07-41-39" src="https://user-images.githubusercontent.com/79769470/173569949-c4c1d7a4-4d4a-471d-9ae5-14aa69ee723d.png">
<img width="722" alt="Snipaste_2022-06-14_07-42-50" src="https://user-images.githubusercontent.com/79769470/173570012-3ed29088-4c13-4f71-9f5b-35dc00c61c5a.png">
<img width="722" alt="Snipaste_2022-06-14_07-45-54" src="https://user-images.githubusercontent.com/79769470/173570085-b31697cf-ef6e-42bb-976f-deb5c828433c.png">

- Ground turns white when Jijimon speaks.
<img width="722" alt="Snipaste_2022-06-14_07-53-43" src="https://user-images.githubusercontent.com/79769470/173571080-7fbe82c5-35c7-4ceb-80e2-b563f779d97e.png">

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/8897848/vita3k.log)

# Recommended labels
- Ingame +
- input bug
- graphics bug
- text missing
- color bug
- crash

**Comment by juanCastroProgra** [comment]
Oh very nice, i'm wait for this game ..... serius very thanks for us work

**Comment by gymzatan** [comment]
# App summary
- App name: Digimon World: Next Order (CHI)
- App serial: PCSH00261
- App version: 1.03

# Vita3K summary
- Version: v0.1.5

# Vita3K summary
- Version: v0.1.5
- Build number: 2683
- Commit hash: https://github.com/vita3k/vita3k/commit/b3a44b5 
- CPU backend: Dynarmic             

# Test environment summary
- Tested by: gymzatan
- OS: Windows 11
- CPU: AMD Ryzen 7 5800H
- GPU: AMD Radeon(TM) Graphics
- RAM: 16 GB

# Issues
Game now does not proceed beyond the intro screen.

# Screenshots
<img width="720" alt="Snipaste_2022-06-19_13-02-18" src="https://user-images.githubusercontent.com/79769470/174498529-bc97dcdd-f44d-4129-9857-aae8355ab131.png">


# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/8936298/vita3k.log)


# Recommended labels
- Intro
- regression

**Comment by Syriusflame** [comment]
how you install the game a can't intall this in vita3k

**Comment by Dansant** [comment]
I want help, to develop the project

**Comment by Zangetsu38** [comment]
duplicate issue, look original, upload your picture on it #214

**Comment by Rewin5** [comment]
I can't instal it too
![Screenshot_20231119_232021_Vita3K](https://github.com/Vita3K/compatibility/assets/108353234/e30f2456-0eb4-46c5-be02-c6673f780ed3)
