### ISSUE TITLE
空蝉之廻[PCSG01011]

### ISSUE THREAD

**Issue by metrolittlewhite** [Vita3K/compatibility#894]
# App summary
- App name: 空蝉之廻
- App serial: PCSG01011
- App version: 1.00

# Vita3K summary
- Version: v0.1.5
- Build number: 2793
- Commit hash: https://github.com/vita3k/vita3k/commit/[054a8119] 
- CPU backend: Dynarmic   

                          

# Test environment summary
- Tested by: ASUS Laptop
- OS: Windows 11
- CPU: AMD Ryzen 7 5800H with Radeon Graphics
- GPU: RTX3050
- RAM: 16 GB

# Issues
Initial interface does not respond. 

# Screenshots
[![0](https://user-images.githubusercontent.com/33452869/185751980-29e199f4-f0e7-4211-8d45-86a49b3a7cfc.png)
![1](https://user-images.githubusercontent.com/33452869/185752018-3b992648-0b83-4a4d-b766-b6c0f77522d7.png)
]((https://?))

# Log

# Recommended labels

- Intro
- crash

**Comment by nishinji** [comment]
Fix the title Utsusemi no Meguri(空蝉の廻) [PCSG01011]
