### ISSUE TITLE
Yuukyuu no Tierblade: Lost Chronicle [PCSG00808]

### ISSUE THREAD

**Issue by salmhofer** [Vita3K/compatibility#938]
# App summary
- App name:  悠久のティアブレイド -Lost Chronicle-
- App serial: PCSG00808
- App version: 1.00

# Vita3K summary
- Version: v0.1.6 2851
- Build number: 2851
- Commit hash: https://github.com/vita3k/vita3k/commit/739c5cc
- CPU backend: Dynarmic

                          

# Test environment summary
- Tested by: salmhofer
- OS: Windows 10
- CPU: Intel Core i5-8400
- GPU: NVIDIA GeForce GTX 1050 Ti
- RAM: 8 GB

# Issues
game crashes at a certain point in chapter 2 but works normally before it

# Screenshots
![1](https://user-images.githubusercontent.com/114970397/193727077-bce7dcda-6838-4d99-b30f-988a2eee997b.png)
![2](https://user-images.githubusercontent.com/114970397/193727122-55dc5fb6-1702-442f-af72-e061f6c8be92.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/9702519/vita3k.log)

# Recommended labels
dynarmic crash
ingame -

**Comment by nishinji** [comment]
this is already exist [https://github.com/Vita3K/compatibility/issues/549](url)
